import {test} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {settings} from '../src/config.js';
import {initialize} from '../src/database.js';
import {captureInput,claimRun,finishRun,renewRun,recoverRuns,prepareRun} from '../src/managed-runs.js';
import {reader} from '../src/access.js';
import type {IncomingMessage} from 'node:http';
import {archiveStatus,digest} from '../src/archive.js';

test('real PostgreSQL: browser originals, files, scoped claims and idempotent results',{skip:!process.env.PGHOST},async()=>{
  const config=settings(),connection={host:process.env.PGHOST,user:'nocheh',database:'nocheh',password:config.databasePassword};
  const root=await mkdtemp(join(tmpdir(),'nocheh-browser-')),namespace='test_browser_'+Date.now();
  const admin=new pg.Pool(connection);await admin.query(`CREATE SCHEMA ${namespace}`);
  const pool=new pg.Pool({...connection,options:`-c search_path=${namespace}`,max:4});
  config.dataDir=root;config.assistant={enabled:false,owner_id:'42',group_ids:['-10']};
  try {
    await initialize(pool);
    const text='  browser original\r\nsecret value\0🙂 ',bytes=Buffer.from([0,255,42,10]);
    const profile='nocheh-'+digest('-10:policy:1').slice(0,24);
    const body={id:'input-one',conversation:'session-one',profile,scope:'-10',space:'-10',revision:1,text,
      files:[{name:'original.bin',kind:'file',bytes_base64:bytes.toString('base64')}]};
    const first=await captureInput(pool,config,body),second=await captureInput(pool,config,body);
    assert.equal(first.event_id,second.event_id);assert.equal(second.duplicate,true);
    assert.deepEqual(await readFile(join(root,'files',first.attachments[0]!.sha256)),bytes);
    await assert.rejects(captureInput(pool,config,{...body,text:'changed'}),/source_identity_conflict/);
    await assert.rejects(captureInput(pool,config,{...body,id:'other',scope:'-20'}),/run_scope_denied/);
    await assert.rejects(captureInput(pool,config,{...body,id:'other',files:[{...body.files[0],name:'../outside'}]}),/invalid_attachment/);
    const claim={event_id:first.event_id,actor:'actor-one',scope:'-10',profile};
    await assert.rejects(claimRun(pool,config,{...claim,profile:'private-profile'}),/run_profile_mismatch/);
    await assert.rejects(claimRun(pool,config,{...claim,scope:'42'}),/captured_run_not_found/);
    const claims=await Promise.all([claimRun(pool,config,claim),claimRun(pool,config,claim)]);
    const won=claims.find(c=>c.claimed)!;
    assert.equal(claims.filter(c=>c.claimed).length,1);assert.equal(won.text,text);
    const principal=reader({headers:{authorization:'Bearer '+won.archive_credential}} as IncomingMessage,config.token);
    assert.equal(principal.scope,'-10');assert.equal(principal.admin,false);assert.equal(principal.turnEvent,first.event_id);
    assert.equal(principal.space,'-10');assert.equal(principal.revision,1);
    await assert.rejects(finishRun(pool,{...claim,actor:'wrong',state:'done',text:'answer',session:'session-one'}),/run_actor_mismatch/);
    const result={...claim,state:'done',text:'Generated answer',session:'session-one'};
    await finishRun(pool,result);assert.equal((await finishRun(pool,result)).duplicate,true);
    await assert.rejects(finishRun(pool,{...result,text:'different'}),/run_result_conflict/);
    const row=(await pool.query('SELECT original_text FROM events WHERE id=$1',[first.event_id])).rows[0];
    assert.deepEqual(row.original_text,Buffer.from(text));
    assert.equal((await pool.query("SELECT content FROM derived_artifacts WHERE event_id=$1 AND kind='browser_result'",[first.event_id])).rows[0].content.toString(),'Generated answer');
    assert.equal((await claimRun(pool,config,claim)).claimed,false);
    assert.equal((await claimRun(pool,config,claim)).text,'Generated answer');
    const restart=await captureInput(pool,config,{...body,id:'restart',files:[]});
    const restartClaim={...claim,event_id:restart.event_id};await claimRun(pool,config,restartClaim);
    await assert.rejects(renewRun(pool,{...restartClaim,actor:'wrong'}),/run_lease_lost/);
    await renewRun(pool,restartClaim);await recoverRuns(pool);
    assert.equal((await claimRun(pool,config,restartClaim)).state,'running');
    await pool.query("UPDATE managed_runs SET lease_until=now()-interval '1 second' WHERE event_id=$1",[restart.event_id]);
    await assert.rejects(renewRun(pool,restartClaim),/run_lease_lost/);
    await recoverRuns(pool);assert.equal((await claimRun(pool,config,restartClaim)).state,'interrupted');
    const late={...restartClaim,state:'done',session:'session-one',text:'late result evidence'};
    assert.equal((await finishRun(pool,late)).state,'interrupted');assert.equal((await finishRun(pool,late)).duplicate,true);
    assert.equal((await claimRun(pool,config,restartClaim)).text,'late result evidence');
    const audio=await captureInput(pool,config,{...body,id:'audio',files:[{name:'voice.wav',kind:'audio',bytes_base64:bytes.toString('base64')},{name:'notes.txt',kind:'file',bytes_base64:Buffer.from('exact file\r\n').toString('base64')}]});
    const audioClaim={...claim,event_id:audio.event_id};await claimRun(pool,config,audioClaim);
    let transcriptions=0;
    const prepared=await prepareRun(pool,config,audioClaim,async(operation)=>{assert.equal(operation,'perception.transcribe');transcriptions++;return {success:true,transcript:'derived transcript'};});
    assert.deepEqual(prepared.transcripts,['derived transcript']);assert.equal(prepared.files.find(f=>f.name==='notes.txt')?.text,'exact file\r\n');
    await prepareRun(pool,config,audioClaim,async()=>{throw Error('must reuse transcript');});assert.equal(transcriptions,1);
    const unavailable=new pg.Pool(connection);await unavailable.end();
    await assert.rejects(captureInput(unavailable,config,{...body,id:'outage',files:[]}));
    assert.equal((await pool.query('SELECT count(*)::int AS count FROM managed_runs')).rows[0].count,3);
    assert.equal((await archiveStatus(pool)).managed_runs.length,3);
    const stale=await captureInput(pool,config,{...body,id:'after-policy-change',files:[]});
    await pool.query('UPDATE memory_policy_state SET revision=revision+1');
    await assert.rejects(claimRun(pool,config,{...claim,event_id:stale.event_id}),{code:'browser_audience_changed'});
  }finally{await pool.end();await admin.query(`DROP SCHEMA ${namespace} CASCADE`);await admin.end();await rm(root,{recursive:true,force:true});}
});
