import {useEffect,useRef,useState} from 'react';
import {useResource,refreshResources} from '../lib/resource';
import {call} from '../lib/page-helpers.js';
import {StatusBadge} from '../components/status';
import {Button,Badge,Tabs,TabsList,TabsTrigger,TabsContent,Table,Sheet,Alert,EmptyState} from '../components/ui/primitives';
import {Source} from './source.js';
type Action={id:string;event_id?:string;fingerprint:string;kind:string;scope:string;profile?:string;logical_profile?:string;arguments:unknown;result?:unknown;state:string;created_at:string};
type Permission={id:string;kind:string;scope:string;arguments:unknown;remaining:number;expires_at:string;revoked_at?:string};
type Run={event_id:string;state:string;created_at:string;channel:string;job_name?:string;job_id?:string;profile:string;scope:string;error_code?:string};
const names:Record<string,string>={shell:'Workspace command',browser:'Read web page',mcp:'MCP tool call',telegram_message:'Telegram message'};
const Json=({value}:{value:unknown})=><pre className="n-data" dir="auto">{JSON.stringify(value,null,2)}</pre>;
const telegramFields=(action:Action)=>action.kind==='telegram_message'&&action.arguments&&typeof action.arguments==='object'?
 action.arguments as {text?:unknown;destination?:unknown}:null;
const actionText=(action:Action)=>{const fields=telegramFields(action);return typeof fields?.text==='string'?fields.text:null;};
const destination=(action:Action)=>{const fields=telegramFields(action);return typeof fields?.destination==='string'?fields.destination:action.scope;};
const actionFromHash=()=>new URLSearchParams(location.hash.split('?')[1]||'').get('action');
export function Activity({notify}:{notify:(message:string,error?:boolean)=>void}){
 const queue=useResource<{actions:Action[];telegram?:Action[];permissions:Permission[]}>('/tools/actions',10000),status=useResource<{archive?:{managed_runs:Run[]}}>('/status',10000);
 const [review,setReview]=useState<Action|null>(null),[sourceId,setSourceId]=useState<string|null>(null),[minutes,setMinutes]=useState(60),[uses,setUses]=useState(3),[busy,setBusy]=useState(false),[problem,setProblem]=useState('');
 const trigger=useRef<HTMLElement|null>(null),actions=[...(queue.data?.actions||[]),...(queue.data?.telegram||[])].sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const pending=actions.filter(item=>item.state==='proposed'),recent=actions.filter(item=>item.state!=='proposed');
 const linkedId=actionFromHash(),linked=useResource<Action>(linkedId&&!actions.some(item=>item.id===linkedId)?'/tools/actions/'+linkedId:null);
 useEffect(()=>{const id=actionFromHash(),found=actions.find(item=>item.id===id)||linked.data;if(found&&found.id===id)setReview(previous=>previous?.id===id?previous:found);},[queue.data,linked.data]);
 const openReview=(item:Action,element:HTMLElement)=>{trigger.current=element;setReview(item);setProblem('');history.replaceState(null,'','#activity?action='+encodeURIComponent(item.id));};
 const closeReview=()=>{setReview(null);if(actionFromHash())history.replaceState(null,'','#activity');};
 const current=actions.find(a=>a.id===review?.id)||(linked.data?.id===review?.id?linked.data:undefined),changed=!!review&&(!current||current.fingerprint!==review.fingerprint),action=changed?review:current;
 const source=useResource<any>(sourceId?'/events/'+sourceId:null),permissions=queue.data?.permissions||[],runs=status.data?.archive?.managed_runs||[];
 const decide=async(route:string,body:unknown)=>{setBusy(true);setProblem('');try{await call('/tools/'+route,body);notify(route==='revoke'?'Permission revoked.':route==='grant'?'Permission saved.':(body as {decision?:string}).decision==='approve'?'Approved. Execution and delivery are tracked separately.':'Action denied.');closeReview();refreshResources();}catch(e){setProblem(e instanceof Error?e.message:'The decision could not be saved.');}finally{setBusy(false);}};
 return <><Tabs defaultValue="approvals"><TabsList aria-label="Activity category"><TabsTrigger value="approvals">Approvals <Badge>{pending.length}</Badge></TabsTrigger><TabsTrigger value="permissions">Permissions</TabsTrigger><TabsTrigger value="runs">Run history</TabsTrigger></TabsList>
 <TabsContent value="approvals"><section className="n-panel approval-panel"><div className="approval-heading"><div><p className="archive-kicker">Your decision needed</p><h2>{pending.length} {pending.length===1?'action':'actions'} awaiting approval</h2><p className="n-muted">Review the exact message or arguments and destination before allowing an action to start.</p></div></div>{queue.error&&<Alert>{queue.data?'Action observations may be stale. Refresh before deciding.':'Approvals are unavailable.'}</Alert>}{linked.error&&<Alert>The linked action could not be loaded. Refresh or open it from the action queue.</Alert>}{!queue.data&&!queue.error&&<p role="status">Loading approvals…</p>}{queue.data&&!pending.length&&<EmptyState title="Nothing to approve">New action requests will appear here with their exact content and destination.</EmptyState>}{pending.length>0&&<div className="approval-list">{pending.map(item=><article className="approval-card" key={item.id}><div className="approval-card-head"><div><span className="approval-kind">{names[item.kind]||item.kind}</span><h3>{item.kind==='telegram_message'?'Send a Telegram message':names[item.kind]||item.kind}</h3></div><StatusBadge state="proposed" label="Needs approval"/></div>{actionText(item)?<blockquote className="approval-message" dir="auto">{actionText(item)}</blockquote>:<p className="n-muted">Inspect the exact operation arguments before deciding.</p>}<div className="approval-meta"><span><b>To</b> {item.kind==='telegram_message'?'Telegram chat '+destination(item):'Scope '+item.scope}</span><span><b>Requested</b> {new Date(item.created_at).toLocaleString()}</span>{item.kind!=='telegram_message'&&<span><b>Profile</b> {item.profile||item.logical_profile||'Default'}</span>}</div><Button variant="default" onClick={e=>openReview(item,e.currentTarget)}>Review and decide</Button></article>)}</div>}{recent.length>0&&<details className="approval-history"><summary>Recent action history ({recent.length})</summary><Table aria-label="Recent actions"><thead><tr><th>Action</th><th>Destination</th><th>Status</th><th>Requested</th><th>Details</th></tr></thead><tbody>{recent.map(item=><tr key={item.id}><td>{names[item.kind]||item.kind}</td><td>{item.kind==='telegram_message'?'Telegram chat '+destination(item):'Scope '+item.scope}</td><td><StatusBadge state={item.state}/></td><td>{new Date(item.created_at).toLocaleString()}</td><td><Button size="sm" onClick={e=>openReview(item,e.currentTarget)}>View details</Button></td></tr>)}</tbody></Table></details>}</section></TabsContent>
 <TabsContent value="permissions"><section className="n-panel"><h2>Standing permissions</h2><p className="n-muted">Only exact matches can start while a permission remains valid. Revocation prevents new starts; it cannot undo an operation already sent.</p>{queue.error&&<Alert>Permission observations may be unavailable or stale.</Alert>}{queue.data&&!permissions.length&&<EmptyState title="No standing permissions">Each action requires review.</EmptyState>}{permissions.map(p=><article className="archive-result" key={p.id}><div className="list-heading"><h3>{names[p.kind]||p.kind}</h3><StatusBadge state={p.revoked_at?'disabled':'allowed'} label={p.revoked_at?'Revoked':p.remaining+' starts left'}/></div><p>Scope {p.scope} · Expires {new Date(p.expires_at).toLocaleString()}</p><details><summary>Exact arguments</summary><Json value={p.arguments}/></details>{!p.revoked_at&&<Button disabled={busy||!!queue.error} onClick={()=>decide('revoke',{id:p.id})}>Revoke permission</Button>}</article>)}{problem&&!review&&<Alert>{problem}</Alert>}</section></TabsContent>
 <TabsContent value="runs"><section className="n-panel"><div className="list-heading"><h2>Conversations and scheduled runs</h2><a href="/hermes/cron">Open Hermes Schedules ↗</a></div><p className="n-muted">Latest 50 captured inputs and schedule fires, including missed and interrupted runs.</p>{status.error&&<Alert>Run observations may be unavailable or stale.</Alert>}{status.data&&!runs.length&&<EmptyState title="No recorded runs">Start a conversation in Hermes Chat or use Schedules.</EmptyState>}{runs.length>0&&<Table aria-label="Conversation run history"><thead><tr><th>Run</th><th>Audience</th><th>Status</th><th>Time</th><th>Evidence</th></tr></thead><tbody>{runs.map(run=><tr key={run.event_id}><td>{run.channel==='scheduler'?(run.job_name||run.job_id):'Browser conversation'}{run.error_code&&<small>{run.error_code.replaceAll('_',' ')}</small>}</td><td>{run.profile}<small>Scope {run.scope}</small></td><td><StatusBadge state={run.state} label={run.state==='captured'?'Captured only':undefined}/></td><td>{new Date(run.created_at).toLocaleString()}</td><td><Button size="sm" onClick={e=>{trigger.current=e.currentTarget;setSourceId(run.event_id);}}>Inspect original</Button></td></tr>)}</tbody></Table>}</section></TabsContent></Tabs>
 <Sheet open={!!review} onOpenChange={open=>{if(!open)closeReview();}} title={action?.kind==='telegram_message'?'Review Telegram message':'Review exact operation'} description="Approval is for this exact content and destination only." returnFocus={trigger.current}>{action&&<div className="approval-review"><StatusBadge state={action.state} label={action.state==='proposed'?'Needs approval':undefined}/>{action.kind==='telegram_message'?<><div className="approval-review-field"><span>Destination</span><strong>Telegram chat {destination(action)}</strong></div><div className="approval-review-field"><span>Exact message to send</span><blockquote className="approval-message" dir="auto">{actionText(action)||'Message content unavailable'}</blockquote></div><p className="n-muted">Requested from conversation {action.scope}. Approval queues delivery; a confirmed send appears as a separate result.</p></>:<><h3>{names[action.kind]||action.kind}</h3><p>Profile: {action.profile||action.logical_profile||'Default'} · Scope: <b>{action.scope}</b></p><div className="approval-review-field"><span>Exact arguments</span><Json value={action.arguments}/></div></>}<small>Requested {new Date(action.created_at).toLocaleString()}</small>{(changed||queue.error)&&<Alert>The action changed or this observation is stale. Close this review and refresh before deciding.</Alert>}{problem&&<Alert>{problem}</Alert>}{action.state==='proposed'&&<div className="n-actions"><Button variant="default" disabled={busy||changed||!!queue.error} onClick={()=>decide(action.kind==='telegram_message'?'telegram-decision':'decide',{id:action.id,fingerprint:action.fingerprint,decision:'approve'})}>{action.kind==='telegram_message'?'Approve message':'Approve action'}</Button><Button disabled={busy||changed||!!queue.error} onClick={()=>decide(action.kind==='telegram_message'?'telegram-decision':'decide',{id:action.id,fingerprint:action.fingerprint,decision:'deny'})}>Deny</Button></div>}{action.result!=null&&<details><summary>Execution result</summary><Json value={action.result}/></details>}<details className="approval-technical"><summary>Technical details</summary><small>Action {action.id}</small>{action.kind==='telegram_message'&&<Json value={action.arguments}/>}</details>{action.kind!=='telegram_message'&&<details><summary>Allow this exact operation again</summary><p>Only these arguments, profile and scope are authorized.</p><label>Expires in minutes (1–1440)<input type="number" min={1} max={1440} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>Maximum starts (1–20)<input type="number" min={1} max={20} value={uses} onChange={e=>setUses(Number(e.target.value))}/></label><Button disabled={busy||changed||!!queue.error||!Number.isInteger(minutes)||minutes<1||minutes>1440||!Number.isInteger(uses)||uses<1||uses>20} onClick={()=>decide('grant',{action_id:action.id,fingerprint:action.fingerprint,minutes,uses})}>Create bounded permission</Button></details>}</div>}</Sheet>
 <Sheet open={!!sourceId} onOpenChange={open=>{if(!open)setSourceId(null);}} title="Run source evidence" returnFocus={trigger.current}>{source.error&&<Alert>Source unavailable. <Button onClick={()=>refreshResources()}>Retry source</Button></Alert>}{source.data?<Source record={source.data} notify={notify}/>:!source.error&&<p role="status">Loading source…</p>}</Sheet></>;
}
