import {useRef,useState} from 'react';
import {useResource,refreshResources} from '../lib/resource';
import {call} from '../lib/page-helpers.js';
import {StatusBadge} from '../components/status';
import {Button,Badge,Tabs,TabsList,TabsTrigger,TabsContent,Table,Sheet,Alert,EmptyState} from '../components/ui/primitives';
import {Source} from './source.js';
type Action={id:string;fingerprint:string;kind:string;scope:string;profile?:string;arguments:unknown;result?:unknown;state:string;created_at:string};
type Permission={id:string;kind:string;scope:string;arguments:unknown;remaining:number;expires_at:string;revoked_at?:string};
type Run={event_id:string;state:string;created_at:string;channel:string;job_name?:string;job_id?:string;profile:string;scope:string;error_code?:string};
const names:Record<string,string>={shell:'Workspace command',browser:'Read web page',mcp:'MCP tool call',telegram_message:'Telegram message'};
const Json=({value}:{value:unknown})=><pre className="n-data" dir="auto">{JSON.stringify(value,null,2)}</pre>;
export function Activity({notify}:{notify:(message:string,error?:boolean)=>void}){
 const queue=useResource<{actions:Action[];telegram?:Action[];permissions:Permission[]}>('/tools/actions',10000),status=useResource<{archive?:{managed_runs:Run[]}}>('/status',10000);
 const [review,setReview]=useState<Action|null>(null),[sourceId,setSourceId]=useState<string|null>(null),[minutes,setMinutes]=useState(60),[uses,setUses]=useState(3),[busy,setBusy]=useState(false),[problem,setProblem]=useState('');
 const trigger=useRef<HTMLElement|null>(null),actions=[...(queue.data?.actions||[]),...(queue.data?.telegram||[])].sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const current=actions.find(a=>a.id===review?.id),changed=!!review&&(!current||current.fingerprint!==review.fingerprint),action=changed?review:current;
 const source=useResource<any>(sourceId?'/events/'+sourceId:null),permissions=queue.data?.permissions||[],runs=status.data?.archive?.managed_runs||[];
 const decide=async(route:string,body:unknown)=>{setBusy(true);setProblem('');try{await call('/tools/'+route,body);notify('Decision saved.');refreshResources();}catch(e){setProblem(e instanceof Error?e.message:'The decision could not be saved.');}finally{setBusy(false);}};
 return <><Tabs defaultValue="approvals"><TabsList aria-label="Activity category"><TabsTrigger value="approvals">Approvals <Badge>{actions.filter(a=>a.state==='proposed').length}</Badge></TabsTrigger><TabsTrigger value="permissions">Permissions</TabsTrigger><TabsTrigger value="runs">Run history</TabsTrigger></TabsList>
 <TabsContent value="approvals"><section className="n-panel"><h2>Actions awaiting your review</h2><p className="n-muted">Inspect exact arguments and audience before execution. Uncertain effects are never retried automatically.</p>{queue.error&&<Alert>{queue.data?'Action observations may be stale.':'Approvals are unavailable.'}</Alert>}{!queue.data&&!queue.error&&<p role="status">Loading approvals…</p>}{queue.data&&!actions.length&&<EmptyState title="No proposed actions">Hermes can propose an operation during a conversation.</EmptyState>}{actions.length>0&&<Table aria-label="Action review queue"><thead><tr><th>Operation</th><th>Audience</th><th>Status</th><th>Created</th><th>Review</th></tr></thead><tbody>{actions.map(item=><tr key={item.id}><td>{names[item.kind]||item.kind}</td><td>Scope {item.scope}<small>{item.profile||'Telegram delivery'}</small></td><td><StatusBadge state={item.state}/></td><td>{new Date(item.created_at).toLocaleString()}</td><td><Button size="sm" onClick={e=>{trigger.current=e.currentTarget;setReview(item);setProblem('');}}>Review operation</Button></td></tr>)}</tbody></Table>}</section></TabsContent>
 <TabsContent value="permissions"><section className="n-panel"><h2>Standing permissions</h2><p className="n-muted">Only exact matches can start while a permission remains valid. Revocation prevents new starts; it cannot undo an operation already sent.</p>{queue.error&&<Alert>Permission observations may be unavailable or stale.</Alert>}{queue.data&&!permissions.length&&<EmptyState title="No standing permissions">Each action requires review.</EmptyState>}{permissions.map(p=><article className="archive-result" key={p.id}><div className="list-heading"><h3>{names[p.kind]||p.kind}</h3><StatusBadge state={p.revoked_at?'disabled':'allowed'} label={p.revoked_at?'Revoked':p.remaining+' starts left'}/></div><p>Scope {p.scope} · Expires {new Date(p.expires_at).toLocaleString()}</p><details><summary>Exact arguments</summary><Json value={p.arguments}/></details>{!p.revoked_at&&<Button disabled={busy||!!queue.error} onClick={()=>decide('revoke',{id:p.id})}>Revoke permission</Button>}</article>)}{problem&&!review&&<Alert>{problem}</Alert>}</section></TabsContent>
 <TabsContent value="runs"><section className="n-panel"><div className="list-heading"><h2>Conversations and scheduled runs</h2><a href="/hermes/cron">Open Hermes Schedules ↗</a></div><p className="n-muted">Latest 50 captured inputs and schedule fires, including missed and interrupted runs.</p>{status.error&&<Alert>Run observations may be unavailable or stale.</Alert>}{status.data&&!runs.length&&<EmptyState title="No recorded runs">Start a conversation in Hermes Chat or use Schedules.</EmptyState>}{runs.length>0&&<Table aria-label="Conversation run history"><thead><tr><th>Run</th><th>Audience</th><th>Status</th><th>Time</th><th>Evidence</th></tr></thead><tbody>{runs.map(run=><tr key={run.event_id}><td>{run.channel==='scheduler'?(run.job_name||run.job_id):'Browser conversation'}{run.error_code&&<small>{run.error_code.replaceAll('_',' ')}</small>}</td><td>{run.profile}<small>Scope {run.scope}</small></td><td><StatusBadge state={run.state} label={run.state==='captured'?'Captured only':undefined}/></td><td>{new Date(run.created_at).toLocaleString()}</td><td><Button size="sm" onClick={e=>{trigger.current=e.currentTarget;setSourceId(run.event_id);}}>Inspect original</Button></td></tr>)}</tbody></Table>}</section></TabsContent></Tabs>
 <Sheet open={!!review} onOpenChange={open=>{if(!open)setReview(null);}} title="Review exact operation" description="Authorization applies only to this operation and audience." returnFocus={trigger.current}>{action&&<><StatusBadge state={action.state}/><h3>{names[action.kind]||action.kind}</h3><p>Profile: {action.profile||'Telegram delivery'} · Scope: <b>{action.scope}</b></p><small>Action {action.id}</small><Json value={action.arguments}/>{(changed||queue.error)&&<Alert>The action changed or its observation is stale. Close this review and refresh before authorizing it.</Alert>}{problem&&<Alert>{problem}</Alert>}{['proposed','approved'].includes(action.state)&&<div className="n-actions"><Button variant="default" disabled={busy||changed||!!queue.error||action.state==='approved'} onClick={()=>decide(action.kind==='telegram_message'?'telegram-decision':'decide',{id:action.id,fingerprint:action.fingerprint,decision:'approve'})}>Approve this operation</Button><Button disabled={busy||changed||!!queue.error||(action.kind==='telegram_message'&&action.state!=='proposed')} onClick={()=>decide(action.kind==='telegram_message'?'telegram-decision':'decide',{id:action.id,fingerprint:action.fingerprint,decision:'deny'})}>Deny</Button></div>}{action.result!=null&&<details><summary>Execution result</summary><Json value={action.result}/></details>}{action.kind!=='telegram_message'&&<details><summary>Allow this exact operation again</summary><p>Only these arguments, profile and scope are authorized.</p><label>Expires in minutes (1–1440)<input type="number" min={1} max={1440} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>Maximum starts (1–20)<input type="number" min={1} max={20} value={uses} onChange={e=>setUses(Number(e.target.value))}/></label><Button disabled={busy||changed||!!queue.error||!Number.isInteger(minutes)||minutes<1||minutes>1440||!Number.isInteger(uses)||uses<1||uses>20} onClick={()=>decide('grant',{action_id:action.id,fingerprint:action.fingerprint,minutes,uses})}>Create bounded permission</Button></details>}</>}</Sheet>
 <Sheet open={!!sourceId} onOpenChange={open=>{if(!open)setSourceId(null);}} title="Run source evidence" returnFocus={trigger.current}>{source.error&&<Alert>Source unavailable. <Button onClick={()=>refreshResources()}>Retry source</Button></Alert>}{source.data?<Source record={source.data} notify={notify}/>:!source.error&&<p role="status">Loading source…</p>}</Sheet></>;
}
