import {useEffect,useState} from 'react';
import {Search,ArrowUpRight} from 'lucide-react';
import {useResource} from '../lib/resource';
import {Button,Badge,EmptyState,Alert,Skeleton} from '../components/ui/primitives';
import {Source} from './source.js';
type RecordRow={id?:string;event_id?:string;derived_id?:string;scope:string;text?:string;snippet?:string;preview?:string;total?:number;ready?:number;channel?:string;received_at?:string};
type Records={records?:RecordRow[];results?:RecordRow[];items?:RecordRow[];next?:string}|RecordRow[];
export function Archive({notify}:{notify:(message:string,error?:boolean)=>void}){
 const [draft,setDraft]=useState(''),[query,setQuery]=useState(''),[pages,setPages]=useState(['']),[selected,setSelected]=useState<string|null>(()=>new URLSearchParams(location.hash.split('?')[1]||'').get('source'));
 useEffect(()=>{const changed=()=>setSelected(new URLSearchParams(location.hash.split('?')[1]||'').get('source'));addEventListener('hashchange',changed);return()=>removeEventListener('hashchange',changed);},[]);
 const after=pages.at(-1)||'',path=query?'/search?q='+encodeURIComponent(query):'/data'+(after?'?after='+encodeURIComponent(after):'');
 const {data,error,loading}=useResource<Records>(path),source=useResource<any>(selected?'/events/'+selected:null);
 const rows=Array.isArray(data)?data:data?.records||data?.results||data?.items||[],visible=rows.filter(r=>!r.derived_id);
 const next=!Array.isArray(data)?data?.next:null;
 return <div><section className="n-panel"><form className="search-toolbar" onSubmit={e=>{e.preventDefault();setQuery(draft.trim());setPages(['']);}}><label className="n-grow">Search your archive<div className="search-input"><Search size={16} aria-hidden="true"/><input type="search" placeholder="Find original messages and source evidence…" value={draft} onChange={e=>setDraft(e.target.value)}/></div></label><Button type="submit" disabled={loading} variant="default">Search</Button>{query&&<Button onClick={()=>{setDraft('');setQuery('');setPages(['']);}}>Clear search</Button>}</form></section>
 <div className={'archive-workspace'+(selected?' has-selection':'')}><section className="n-panel archive-list" aria-label="Archive results"><div className="list-heading"><h2>{query?'Search results':'Original records'}</h2><Badge>{visible.length} on this page</Badge></div>{error&&<Alert>{data?'Results may be stale.':'Archive results are unavailable.'}</Alert>}{!data&&loading&&<Skeleton className="chart-skeleton"/>}{data&&!visible.length&&<EmptyState title="No matching records">Try different original message text. Generated versions are linked from source details.</EmptyState>}{visible.map((r,i)=>{const id=r.event_id||r.id;return <article key={(id||i)+':'+(r.derived_id||'')} className={'archive-result'+(selected===id?' selected':'')}><div className="result-meta"><Badge>{r.derived_id?'Generated text match':'Original record'}</Badge><span>Scope {r.scope}</span></div><p dir="auto">{r.text||r.snippet||r.preview||'(No message text)'}</p>{r.received_at&&<small>{new Date(r.received_at).toLocaleString()}</small>}{r.total!==undefined&&<small>{r.ready} / {r.total} guarded copies ready</small>}<Button size="sm" onClick={()=>setSelected(id||null)} disabled={!id} aria-pressed={selected===id}>Inspect source <ArrowUpRight size={13}/></Button></article>;})}<div className="n-actions"><Button disabled={pages.length===1||!!query} onClick={()=>setPages(p=>p.slice(0,-1))}>Previous records</Button><small>Page {pages.length}</small><Button disabled={!next||!!query} onClick={()=>setPages(p=>[...p,next!])}>Next records</Button></div></section><section className="archive-detail" aria-label="Source details">{selected?<><div className="detail-heading"><h2>Source evidence</h2><Button size="sm" onClick={()=>setSelected(null)}>Close source</Button></div>{source.error&&<Alert>The source is unavailable. Choose it again or refresh to retry.</Alert>}{!source.data&&!source.error&&<Skeleton className="chart-skeleton"/>}{source.data&&<Source record={source.data} notify={notify}/>}</>:<div className="n-panel"><EmptyState title="Inspect the evidence">Choose a record to compare its immutable original, guarded copies, generated text, and provenance.</EmptyState></div>}</section></div></div>;
}
