import {useEffect,useState} from 'react';
import {Search,PencilLine} from 'lucide-react';
import {useResource} from '../lib/resource';
import {Button,Badge,EmptyState,Alert,Skeleton,Table} from '../components/ui/primitives';
import {Source} from './source.js';
type RecordRow={id?:string;event_id?:string;derived_id?:string;scope:string;text?:string;snippet?:string;preview?:string;total?:number;ready?:number;channel?:string;received_at?:string};
type Records={records?:RecordRow[];results?:RecordRow[];items?:RecordRow[];next?:string}|RecordRow[];
export function Archive({notify}:{notify:(message:string,error?:boolean)=>void}){
 const [draft,setDraft]=useState(''),[query,setQuery]=useState(''),[pages,setPages]=useState(['']),[selected,setSelected]=useState<string|null>(()=>new URLSearchParams(location.hash.split('?')[1]||'').get('source'));
 useEffect(()=>{const changed=()=>setSelected(new URLSearchParams(location.hash.split('?')[1]||'').get('source'));addEventListener('hashchange',changed);return()=>removeEventListener('hashchange',changed);},[]);
 useEffect(()=>{if(!selected)return;requestAnimationFrame(()=>document.querySelector<HTMLElement>('.archive-detail')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));},[selected]);
 const after=pages.at(-1)||'',path=query?'/search?q='+encodeURIComponent(query):'/data'+(after?'?after='+encodeURIComponent(after):'');
 const {data,error,loading}=useResource<Records>(path),source=useResource<any>(selected?'/events/'+selected:null);
 const rows=Array.isArray(data)?data:data?.records||data?.results||data?.items||[],visible=rows.filter(r=>!r.derived_id);
 const next=!Array.isArray(data)?data?.next:null;
 return <div><section className="n-panel"><form className="search-toolbar" onSubmit={e=>{e.preventDefault();setQuery(draft.trim());setPages(['']);}}><label className="n-grow">Search your archive<div className="search-input"><Search size={16} aria-hidden="true"/><input type="search" placeholder="Find original messages and source evidence…" value={draft} onChange={e=>setDraft(e.target.value)}/></div></label><Button type="submit" disabled={loading} variant="default">Search</Button>{query&&<Button onClick={()=>{setDraft('');setQuery('');setPages(['']);}}>Clear search</Button>}</form></section>
 <div className={'archive-workspace'+(selected?' has-selection':'')}><section className="n-panel archive-list" aria-label="Archive results"><div className="list-heading"><div><h2>{query?'Search results':'Original records'}</h2><p className="n-muted archive-table-help">Originals are read-only. Select a row to inspect it and edit its guarded version.</p></div><Badge>{visible.length} on this page</Badge></div>{error&&<Alert>{data?'Results may be stale.':'Archive results are unavailable.'}</Alert>}{!data&&loading&&<Skeleton className="chart-skeleton"/>}{data&&!visible.length&&<EmptyState title="No matching records">Try different original message text. Generated versions are linked from source details.</EmptyState>}{!!visible.length&&<Table aria-label="Archive records"><thead><tr><th>Record</th><th>Scope</th><th>Received</th><th>Guarded</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map((r,i)=>{const id=r.event_id||r.id,text=r.text||r.snippet||r.preview||'(No message text)';return <tr key={(id||i)+':'+(r.derived_id||'')} className={selected===id?'selected':undefined}><td><div className="archive-record-cell"><Badge>{r.derived_id?'Generated match':'Original'}</Badge><span dir="auto" title={text}>{text}</span></div></td><td><code>{r.scope}</code></td><td>{r.received_at?<time dateTime={r.received_at}>{new Date(r.received_at).toLocaleString()}</time>:'—'}</td><td>{r.total!==undefined?<span>{r.ready} / {r.total} ready</span>:'—'}</td><td><Button size="sm" onClick={()=>setSelected(id||null)} disabled={!id} aria-pressed={selected===id} aria-label={'View and edit record '+(id||i)}><PencilLine size={13} aria-hidden="true"/>View / edit</Button></td></tr>;})}</tbody></Table>}<div className="n-actions archive-pager"><Button disabled={pages.length===1||!!query} onClick={()=>setPages(p=>p.slice(0,-1))}>Previous records</Button><small>Page {pages.length}</small><Button disabled={!next||!!query} onClick={()=>setPages(p=>[...p,next!])}>Next records</Button></div></section><section className="archive-detail" aria-label="Source details">{selected?<><div className="detail-heading"><div><h2>Record details</h2><p className="n-muted">The original stays read-only. Editable guarded copies save as new revisions.</p></div><Button size="sm" onClick={()=>setSelected(null)}>Close record</Button></div>{source.error&&<Alert>The source is unavailable. Choose it again or refresh to retry.</Alert>}{!source.data&&!source.error&&<Skeleton className="chart-skeleton"/>}{source.data&&<Source record={source.data} notify={notify}/>}</>:<div className="n-panel"><EmptyState title="Select a record">Choose a table row to compare its immutable original, edit its guarded copy, and inspect provenance.</EmptyState></div>}</section></div></div>;
}
