import {React,sdk,h,useState,useEffect,useRef,useMemo,base,call,button,errorText,labels,Panel,Data,friendlyState,jobName,profileName,Details,RouteLink,Steps,download,exportJSON,useLoad,useResource,refreshResources,StatusBadge,Button,Badge,Alert,Progress,Table,Tabs,TabsList,TabsTrigger,TabsContent,Modal,Sheet,EmptyState} from '../lib/page-helpers.js';
  function OperationResult({result}) {
    if(result.containers)return h('div',null,result.execution_holds&&Object.values(result.execution_holds).some(Boolean)&&h('p',{role:'status'},'This restored installation is held for inspection. Review pending work before activating it.'),...result.containers.map(c=>h('div',{className:'n-row',key:c.service},h('div',null,h('b',null,c.service),h('p',{className:'n-muted'},[c.tool,c.location,c.purpose].filter(Boolean).join(' · '))),h('div',null,h(StatusBadge,{state:c.state}),c.expected_state&&h('small',null,'Expected '+c.expected_state)))),h(Details,{value:result,label:'Full diagnostics'}));
    const messages={backed_up:'Full backup created.',restored_inactive:'Backup restored into a separate inactive installation. Telegram and the copied login remain disabled.',exported:'Portable archive ZIP ready to download.',restarted:'Services restarted and readiness checked.',applied:'Saved settings applied to running services.',apply_failed:result.rolled_back?'Applying settings failed. The previous configuration was restored.':'Applying settings failed. Check diagnostics before trying again.'};
    return h('div',null,h('p',null,messages[result.status]||'Task finished. See details for its result.'),
      result.status==='exported'&&h('p',{className:'n-muted'},result.events+' source records · '+result.files+' original files'+(result.native_profiles!==undefined?' · '+result.native_profiles+' native profiles':'')),
      result.status==='restored_inactive'&&h('p',{className:'n-muted'},(result.verified_tables?.length||0)+' tables verified · '+result.verified_state_files+' state files verified'),h(Details,{value:result}));
  }
export function Operations({notify}){
    const [tick,setTick]=useState(0),{data:listing,error:listError}=useResource('/operations',10000,tick),{data:jobs,error:jobsError}=useResource('/jobs',10000,tick),[review,setReview]=useState(''),[backup,setBackup]=useState(''),[port,setPort]=useState(8795),[busy,setBusy]=useState(false);

    const reviewTrigger=useRef(null);
    const openReview=(action,event)=>{reviewTrigger.current=event.currentTarget;setReview(action);};
    const run=async action=>{setBusy(true);try{await call('/operations',{action,options:action==='restore'?{backup,port}:undefined});setReview('');setTick(v=>v+1);notify('Task started. Follow its progress in Recent maintenance below.');}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
    const descriptions={backup:'Pause archive writers, save a consistent database, files and runtime snapshot, then resume those services. This local backup includes private state and credentials.',restart:'Restart Hermes and the archive workers, then check readiness. Telegram replies may be briefly interrupted.',restore:'Restore the selected backup into a new, separate local installation. Telegram stays disabled and the copied subscription login stays inactive. Your current installation is not replaced.'};
    const tasks=(jobs||[]).filter(j=>j.kind!=='import');
    return h('div',null,h('div',{className:'n-operation-grid'},...[
      ['portable-export','Export archive and memory','Download originals, file bytes, generated results and native notes/session databases. Operational credentials are excluded.','Export archive & memory ZIP'],
      ['diagnose','Check service health','Inspect containers and archive readiness without changing your data.','Run diagnostics'],
      ['export','Download your archive','Create a portable ZIP of original source records and files.','Prepare archive ZIP'],
      ['backup','Back up the installation','Save the database, files and Hermes runtime state, including credentials, locally.','Review full backup'],
      ['restart','Restart services','Restart the assistant and workers. Wait for active imports to finish.','Review restart']
    ].map(([action,title,note,label])=>h(Panel,{key:action,title,note},button(label,event=>['backup','restart'].includes(action)?openReview(action,event):run(action),busy)))),
      h(Panel,{title:'Saved backups'},listError&&h('p',{role:'alert'},listError),!listing&&!listError&&h('p',{role:'status'},'Loading saved backups…'),listing&&h('p',{className:'n-muted'},listing.backups.length?listing.backups.length+' local backup'+(listing.backups.length===1?'':'s')+' available. Restore creates a separate installation for verification.':'No backups yet. Create a full backup above to enable an inactive restore.'),
        h('details',null,h('summary',null,'Advanced · restore a backup into an inactive installation'),h('p',{className:'n-muted'},descriptions.restore),
          h('div',{className:'n-form'},h('label',null,'Saved backup',h('select',{value:backup,onChange:e=>{setBackup(e.target.value);setReview('');}},h('option',{value:''},'Choose a backup'),...(listing?.backups||[]).map(b=>h('option',{key:b.id,value:b.id},new Date(b.created_at).toLocaleString()+' · '+b.files+' files')))),
          h('label',null,'Local port for the inactive installation',h('input',{type:'number',min:1024,max:65535,value:port,onChange:e=>{setPort(Number(e.target.value));setReview('');}}))),button('Review inactive restore',event=>openReview('restore',event),!backup||busy))),
      h(Modal,{returnFocus:reviewTrigger.current,open:!!review,onOpenChange:open=>{if(!open)setReview('');},title:'Review '+({backup:'full backup',restart:'service restart',restore:'inactive restore'})[review]},h('p',null,descriptions[review]),review==='restore'&&h('p',null,'Backup '+backup+' · local port '+port),h('div',{className:'n-actions'},button('Confirm '+review,()=>run(review),busy,'n-primary'),button('Cancel',()=>setReview('')))),
      h(Panel,{title:'Recent maintenance',note:'Diagnostics, exports, backups, restarts, restores and settings applies. Results update automatically.'},jobsError&&h('p',{role:'alert'},jobsError),jobs&&!tasks.length&&h('p',{className:'n-empty'},'No maintenance tasks yet. Run diagnostics above to check the installation.'),
        ...tasks.map(j=>h('article',{className:'n-result',key:j.id},h('div',{className:'n-result-heading'},h('h3',null,jobName(j.kind)),h(StatusBadge,{state:j.state,label:friendlyState(j.state)})),h('small',null,new Date(j.created_at).toLocaleString()),j.error&&h('p',{role:'alert'},j.error),j.result&&h('details',null,h('summary',null,'Inspect result'),h(OperationResult,{result:j.result})),['operations.export','operations.portable-export'].includes(j.kind)&&j.state==='complete'&&button('Download ZIP',()=>download('/exports/'+j.id+'/download','nocheh-archive.zip',notify))))));
  }
