import {useMemo,useState} from 'react';
import {Alert,Badge,Button,EmptyState,Sheet} from '../components/ui/primitives';
import {CursorButtons,EvidenceLinks,Provenance,ResourceState,useOwnerCommand} from '../lib/owner-controls';
import {useResource} from '../lib/resource';

type NodeKind='person'|'project'|'conversation'|'topic'|'fact';
type Node={id:string;kind:NodeKind;label:string;state?:string;detail?:Record<string,any>};
type Edge={id:string;kind:'relationship'|'project_assignment'|'access'|'suggestion';source:string;target:string;state?:string;label?:string;authoritative:boolean;detail?:Record<string,any>};
type MapData={nodes:Node[];edges:Edge[];next:string|null;counts:{nodes:number;edges:number}};
type Request={id:string;destination:string;state:string;revision:number;expires_at:string;wording:string|null;relationship_path:string[];evidence:{id:string}[];provenance:unknown};
type Grant={id:string;destination:string;fact_revision:number;mode:string;state:string;revision:number;wording:string|null;suspended_reason:string|null;provenance:unknown};

const kindLabels:Record<NodeKind,string>={person:'Person',project:'Project',conversation:'Conversation',topic:'Topic',fact:'Memory fact'};
const kindDescriptions:Record<NodeKind,string>={person:'Someone Nocheh remembers',project:'Organizes work; grants no access',conversation:'A chat or group with its own access',topic:'A separate access scope inside a group',fact:'A specific remembered statement'};
const edgeLabels:Record<Edge['kind'],string>={relationship:'Related context',project_assignment:'In project',access:'Access granted',suggestion:'Suggested share'};
const edgeDescriptions:Record<Edge['kind'],string>={relationship:'Description only; no access',project_assignment:'Organization only; no access',access:'This fact can be used here',suggestion:'Waiting for your review'};
const colors:Record<NodeKind,string>={person:'#387bbd',project:'#7357a8',conversation:'#25816f',topic:'#d07135',fact:'#7a858c'};
function columns(nodes:Node[]){const grouped:Record<NodeKind,Node[]>={person:[],project:[],conversation:[],topic:[],fact:[]};for(const node of nodes)grouped[node.kind].push(node);return grouped;}
function layout(nodes:Node[]){const grouped=columns(nodes);
 const xs:Record<NodeKind,number>={person:120,project:350,conversation:650,topic:870,fact:1090},positions=new Map<string,{x:number;y:number}>();
 for(const kind of Object.keys(grouped) as NodeKind[])grouped[kind].sort((a,b)=>a.id.localeCompare(b.id)).forEach((node,index)=>positions.set(node.id,{x:xs[kind],y:75+index*96}));return positions;}
function MapLegend(){return <section className="memory-map-guide" aria-labelledby="memory-map-guide-title"><div className="memory-map-guide-heading"><h3 id="memory-map-guide-title">How to read this map</h3><p>Select any circle or connection to inspect its details.</p></div><div className="memory-map-legend-group"><h4>Circles</h4><dl>{(Object.keys(kindLabels) as NodeKind[]).map(kind=><div key={kind}><dt><span className={'memory-map-node-key '+kind}/>{kindLabels[kind]}</dt><dd>{kindDescriptions[kind]}</dd></div>)}</dl></div><div className="memory-map-legend-group"><h4>Connections</h4><dl>{(Object.keys(edgeLabels) as Edge['kind'][]).map(kind=><div key={kind}><dt><span className={'memory-map-edge-key '+kind}/>{edgeLabels[kind]}</dt><dd>{edgeDescriptions[kind]}</dd></div>)}</dl></div></section>;}
function GraphView({data,showFacts,onSelect}:{data:MapData;showFacts:boolean;onSelect:(value:Node|Edge)=>void}){
 const visible=data.nodes.filter(node=>showFacts||node.kind!=='fact'),ids=new Set(visible.map(node=>node.id)),positions=useMemo(()=>layout(visible),[data,showFacts]),edges=data.edges.filter(edge=>ids.has(edge.source)&&ids.has(edge.target)),height=Math.max(260,160+(Math.max(...Object.values(columns(visible)).map(group=>group.length),1)-1)*96);
 return <div className="memory-map-canvas" role="region" aria-label="Memory relationship and access graph"><svg viewBox={`0 0 1210 ${height}`} role="img" aria-labelledby="memory-map-title"><title id="memory-map-title">People, projects, conversations, facts, relationships, and explicit access</title>
  {edges.map(edge=>{const a=positions.get(edge.source)!,b=positions.get(edge.target)!,x=(a.x+b.x)/2,y=(a.y+b.y)/2;return <g key={edge.id} className="memory-map-edge-target" onClick={()=>onSelect(edge)} role="button" tabIndex={0} aria-label={`${edgeLabels[edge.kind]}: ${edgeDescriptions[edge.kind]}`} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(edge);}}}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={'memory-map-edge '+edge.kind}/><text className="memory-map-edge-label" x={x} y={y-9} textAnchor="middle">{edgeLabels[edge.kind]}</text></g>;})}
  {visible.map(node=>{const point=positions.get(node.id)!;return <g key={node.id} transform={`translate(${point.x} ${point.y})`} className={'memory-map-node '+node.kind} role="button" tabIndex={0} aria-label={`${kindLabels[node.kind]}: ${node.label}`} onClick={()=>onSelect(node)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(node);}}}><circle r={node.kind==='fact'?19:27} fill={colors[node.kind]}/><text x="0" y="4" textAnchor="middle">{node.kind==='fact'?'•':node.label.slice(0,2).toUpperCase()}</text><text className="node-kind" x="0" y={node.kind==='fact'?39:48} textAnchor="middle">{kindLabels[node.kind]}</text><text className="node-label" x="0" y={node.kind==='fact'?55:64} textAnchor="middle">{node.label.slice(0,24)}</text></g>;})}
 </svg></div>;
}
function RequestRow({item,onChanged}:{item:Request;onChanged:()=>void}){const [wording,setWording]=useState(item.wording??''),[mode,setMode]=useState<'one_time'|'persistent'>('one_time'),command=useOwnerCommand();
 const decide=async(decision:'one_time'|'persistent'|'reject')=>{if(await command.run('/memory-access/requests/'+item.id+'/decide',{decision,expected_revision:item.revision,...(decision==='reject'?{}:{wording})}))onChanged();};
 return <article><div className="list-heading"><h3>{item.destination}</h3><Badge>{item.state}</Badge></div><p className="memory-prose">{item.wording}</p><p className="n-muted">Related through {item.relationship_path.join(' → ')||'confirmed evidence'} · expires {new Date(item.expires_at).toLocaleString()}</p><EvidenceLinks sources={item.evidence}/>
  {item.state==='pending'&&<><label>Safe wording<textarea rows={4} maxLength={12000} value={wording} onChange={event=>setWording(event.target.value)}/></label><label>Approval mode<select value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="one_time">One-time (default)</option><option value="persistent">Persistent until revoked</option></select></label>{command.error&&<Alert>{command.error}</Alert>}<div className="n-actions"><Button variant="default" disabled={command.busy||!wording.trim()} onClick={()=>void decide(mode)}>Approve</Button><Button disabled={command.busy} onClick={()=>void decide('reject')}>Reject once</Button></div></>}
  <Provenance value={item.provenance} label="Owner-only provenance"/></article>;
}
function GrantRow({item,onChanged}:{item:Grant;onChanged:()=>void}){const command=useOwnerCommand();return <article><div className="list-heading"><h3>{item.destination}</h3><Badge>{item.state}</Badge></div><p className="memory-prose">{item.wording}</p><p className="n-muted">{item.mode.replace('_',' ')} · fact revision {item.fact_revision}{item.suspended_reason?' · '+item.suspended_reason.replaceAll('_',' '):''}</p>{command.error&&<Alert>{command.error}</Alert>}{['active','suspended'].includes(item.state)&&<Button variant="destructive" disabled={command.busy} onClick={async()=>{if(await command.run('/memory-access/grants/'+item.id+'/revoke',{expected_revision:item.revision}))onChanged();}}>Revoke access</Button>}<Provenance value={item.provenance} label="Owner-only provenance"/></article>;}
function ManualGrant({fact}:{fact:Node}){const [destination,setDestination]=useState(''),[wording,setWording]=useState(fact.label),command=useOwnerCommand();return <form className="owner-form" onSubmit={event=>{event.preventDefault();void command.run('/memory-access/grants',{fact_id:fact.id.slice(5),fact_revision:fact.detail?.revision,destination,wording});}}><h3>Persistent fact grant</h3><p className="n-muted">Grant this exact guarded wording to one concrete group or topic until revoked.</p><label>Destination<input value={destination} onChange={event=>setDestination(event.target.value)} placeholder="-10042 or -10042/topic/7" required/></label><label>Safe wording<textarea rows={4} maxLength={12000} value={wording} onChange={event=>setWording(event.target.value)} required/></label>{command.error&&<Alert>{command.error}</Alert>}<Button type="submit" variant="default" disabled={command.busy||!destination.trim()||!wording.trim()}>Grant persistent access</Button></form>;}
function EdgeDetail({edge,onChanged}:{edge:Edge;onChanged:()=>void}){const command=useOwnerCommand(),detail=edge.detail??{};return <><p className="memory-prose">{detail.wording}</p>{detail.destination&&<p><strong>Destination</strong> {detail.destination}</p>}{Array.isArray(detail.evidence)&&<EvidenceLinks sources={detail.evidence}/>} {detail.history&&<p><a href={String(detail.history).replace(/^\/v1/,'/api/nocheh')} target="_blank" rel="noreferrer">Open correction history</a></p>}{edge.kind==='access'&&detail.grant_id&&['active','suspended'].includes(edge.state??'')&&<Button variant="destructive" disabled={command.busy} onClick={async()=>{if(await command.run('/memory-access/grants/'+detail.grant_id+'/revoke',{expected_revision:detail.revision}))onChanged();}}>Revoke this access</Button>}{command.error&&<Alert>{command.error}</Alert>}<Provenance value={edge} label="Technical details"/></>;}
function AccessReview(){const [revision,setRevision]=useState(0),requests=useResource<{requests:Request[]}>('/memory-access/requests',0,revision),grants=useResource<{grants:Grant[]}>('/memory-access/grants',0,revision),changed=()=>setRevision(value=>value+1);
 return <><section className="n-panel"><div className="list-heading"><div><h2>Fact share requests</h2><p className="n-muted">Each suggestion is private. Rejection closes this request only.</p></div><Badge>{requests.data?.requests.filter(item=>item.state==='pending').length??0} pending</Badge></div><ResourceState {...requests} hasData={!!requests.data}/>{requests.data&&!requests.data.requests.length&&<EmptyState title="No fact requests">High-relevance suggestions appear after the group receives its scoped answer.</EmptyState>}<div className="owner-records">{requests.data?.requests.map(item=><RequestRow key={item.id} item={item} onChanged={changed}/>)}</div></section>
 <section className="n-panel"><h2>Fact grants</h2><p className="n-muted">Persistent grants can be recalled only by their exact group or topic. One-time grants are consumed after confirmed delivery.</p><ResourceState {...grants} hasData={!!grants.data}/><div className="owner-records">{grants.data?.grants.map(item=><GrantRow key={item.id} item={item} onChanged={changed}/>)}</div></section></>;
}
function Settings(){const data=useResource<any>('/memory-access/settings'),command=useOwnerCommand(),[destination,setDestination]=useState('');if(!data.data)return <ResourceState {...data} hasData={false}/>;const global=data.data.settings.find((row:any)=>row.destination==='*'),override=data.data.settings.find((row:any)=>row.destination===destination);
 const fields=(prefix:string,values:any)=><><div className="search-toolbar"><label>Suggestions<select name={prefix+'suggestions'} defaultValue={values.suggestions??global.suggestions}><option value="related">Related entities only</option><option value="off">Off</option></select></label><label>Default approval<select name={prefix+'default_grant_mode'} defaultValue={values.default_grant_mode??global.default_grant_mode}><option value="one_time">One-time</option><option value="persistent">Persistent</option></select></label><label>Request lifetime (seconds)<input name={prefix+'request_ttl_seconds'} type="number" min="60" max="2592000" defaultValue={values.request_ttl_seconds??global.request_ttl_seconds}/></label></div><label><input name={prefix+'notify_owner'} type="checkbox" defaultChecked={values.notify_owner??global.notify_owner}/> Send content-free owner notification</label><label><input name={prefix+'auto_followup'} type="checkbox" defaultChecked={values.auto_followup??global.auto_followup}/> Send approved follow-up automatically</label></>;
 const values=(form:FormData,prefix:string)=>({suggestions:form.get(prefix+'suggestions'),notify_owner:form.get(prefix+'notify_owner')==='on',auto_followup:form.get(prefix+'auto_followup')==='on',request_ttl_seconds:Number(form.get(prefix+'request_ttl_seconds')),default_grant_mode:form.get(prefix+'default_grant_mode')});
 return <details className="n-panel"><summary>Suggestion and delivery settings</summary><h3>Global defaults</h3><form className="owner-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);await command.run('/memory-access/settings',{destination:'*',...values(form,'global_'),expected_revision:global.revision});}}>{fields('global_',global)}<Button type="submit" variant="default" disabled={command.busy}>Save defaults</Button></form><h3>Group or topic override</h3><form key={destination+':'+(override?.revision??0)} className="owner-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);await command.run('/memory-access/settings',{destination,...values(form,'override_'),expected_revision:override?.revision??1});}}><label>Exact destination<input value={destination} onChange={event=>setDestination(event.target.value)} placeholder="-10042 or -10042/topic/7" required/></label>{fields('override_',override??{})}<Button type="submit" disabled={command.busy||!destination.trim()}>Save destination override</Button></form>{command.error&&<Alert>{command.error}</Alert>}</details>;
}
export function MemoryMap(){const [query,setQuery]=useState(''),[kind,setKind]=useState(''),[state,setState]=useState(''),[pages,setPages]=useState(['']),[showFacts,setShowFacts]=useState(false),[selected,setSelected]=useState<Node|Edge|null>(null),[revision,setRevision]=useState(0);
 const params=new URLSearchParams({after:pages.at(-1)!,limit:'180',q:query,...(kind?{kind}:{}),...(state?{state}:{})}),data=useResource<MapData>('/memory-map?'+params,0,revision),factsVisible=showFacts||kind==='fact',pageFacts=data.data?.nodes.filter(node=>node.kind==='fact').length??0,shown=data.data?.nodes.filter(node=>factsVisible||node.kind!=='fact').length??0;
 return <><section className="n-panel"><div className="memory-map-heading"><div><h2>Memory relationships and access</h2><p className="n-muted">See who and what Nocheh remembers, and where a fact is allowed to be used.</p></div><Badge>{data.data?`${shown} shown${!factsVisible&&pageFacts?` · ${pageFacts} facts hidden`:''} · ${data.data.counts.edges} connections total`:'Loading'}</Badge></div><MapLegend/><div className="search-toolbar"><label>Search<input type="search" value={query} onChange={event=>{setQuery(event.target.value);setPages(['']);}}/></label><label>Node type<select value={kind} onChange={event=>{setKind(event.target.value);setPages(['']);}}><option value="">All</option><option value="person">People</option><option value="project">Projects</option><option value="conversation">Conversations</option><option value="topic">Topics</option><option value="fact">Facts</option></select></label><label>Access or item state<input value={state} onChange={event=>{setState(event.target.value);setPages(['']);}} placeholder="pending, active…"/></label><Button aria-pressed={factsVisible} disabled={kind==='fact'} onClick={()=>setShowFacts(value=>!value)}>{kind==='fact'?'Memory facts selected':showFacts?'Hide memory facts':'Show memory facts'}</Button></div><ResourceState {...data} hasData={!!data.data}/>{data.data&&<GraphView data={data.data} showFacts={factsVisible} onSelect={setSelected}/>}<CursorButtons pages={pages} next={data.data?.next} onChange={setPages}/>
 <details className="memory-map-list"><summary>Complete list fallback</summary><ul>{data.data?.nodes.map(node=><li key={node.id}><button onClick={()=>setSelected(node)}><strong>{node.label}</strong> <span>{node.kind}{node.state?' · '+node.state:''}</span></button></li>)}</ul></details></section><Settings/><AccessReview/>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}} title={selected&&'source' in selected?selected.kind:selected?.label??'Memory detail'} description={selected&&'authoritative' in selected?(selected.authoritative?'This edge grants access.':'This edge is descriptive and grants no access.'):'Owner-only memory detail'}>{selected&&'source' in selected?<EdgeDetail edge={selected} onChanged={()=>setRevision(value=>value+1)}/>:selected&&<Provenance value={selected} label="Technical details"/>}{selected&&'label' in selected&&selected.kind==='fact'&&selected.id.startsWith('fact:')&&!selected.id.startsWith('fact:release-')&&<ManualGrant fact={selected}/>}</Sheet></>;
}
