import {Archive,FileText,Activity,Clock3,ArrowUpRight,TriangleAlert} from 'lucide-react';
import {useResource} from '../lib/resource';
import {StatusBadge} from '../components/status';
import {Alert,Skeleton} from '../components/ui/primitives';
import {Analytics} from '../components/analytics';
type Count={state:string;count:number};
type Status={archive?:{events:number;artifacts:Count[]};guard_mode?:string};
type Monitor={application?:{ok:boolean};runtime?:{status?:{telegram:string}};telegram_enabled:boolean;workflows?:{unavailable?:boolean;counts:Count[];workers:{connected:boolean}[]};services?:{service:string;state:string}[]};
export function Status(){
 const archive=useResource<Status>('/status',10000),monitor=useResource<Monitor>('/monitoring',10000),data=archive.data,health=monitor.data;
 const rows=health?.workflows?.unavailable?null:health?.workflows?.counts;
 const count=(states:string[])=>rows?rows.filter(r=>states.includes(r.state)).reduce((n,r)=>n+r.count,0):null;
 const failed=count(['failed','retryable_failed']),uncertain=count(['ambiguous']),unhealthy=health?.services?.filter(s=>s.state==='unhealthy')||[],stale=health?.workflows?.workers?.filter(w=>!w.connected).length||0;
 const metrics=[{title:'Original records',value:data?.archive?.events,Icon:Archive,note:'Preserved source evidence',link:'archive'},{title:'Files ready',value:data?.archive?.artifacts?.filter(r=>r.state==='ready').reduce((n,r)=>n+r.count,0),Icon:FileText,note:'Original files available',link:'archive'},{title:'Running workflows',value:count(['running']),Icon:Activity,note:'Across all workflow families',link:'monitoring'},{title:'Waiting workflows',value:count(['queued','waiting']),Icon:Clock3,note:'Queued or awaiting prerequisites',link:'monitoring'}];
 return <div><div className="health-strip" aria-label="Current system status"><StatusBadge state={monitor.error?'stale':health?.application?.ok?'ready':health?.application?.ok===false?'failed':'unknown'} label={monitor.error?'Observations stale':health?.application?.ok?'API ready':health?.application?.ok===false?'API unavailable':'API unobserved'}/><StatusBadge state={health?.runtime?.status?.telegram} label={'Telegram · '+(health?.runtime?.status?.telegram||'unknown')}/><StatusBadge state={data?.guard_mode} label={'Guard · '+(data?.guard_mode||'unknown')}/><a href="#monitoring">System monitoring <ArrowUpRight size={13}/></a></div>
 {(archive.error||monitor.error)&&<Alert>Some observations are unavailable. Previously loaded values may be stale.</Alert>}
 <div className="overview-metrics">{metrics.map(({title,value,Icon,note,link})=><a className="n-panel metric-card" href={'#'+link} key={title}><div><span>{title}</span><Icon size={17}/></div><strong>{value==null?(archive.loading||monitor.loading?<Skeleton/>:'—'):value.toLocaleString()}</strong><small>{note}</small></a>)}</div>
 {(!!failed||!!uncertain||unhealthy.length>0||stale>0)&&<section className="attention-panel"><TriangleAlert size={19} aria-hidden="true"/><div><h2>Needs your attention</h2><p>{[failed?`${failed} failed workflows`:null,uncertain?`${uncertain} uncertain effects`:null,unhealthy.length?`${unhealthy.length} unhealthy services`:null,stale?`${stale} stale worker observations`:null].filter(Boolean).join(' · ')}</p></div><a href="#monitoring">Review status <ArrowUpRight size={15}/></a></section>}
 <Analytics compact/>
 <div className="n-shortcuts">{[['imports','Bring in a chat','Import your Telegram history.'],['archive','Find source evidence','Search originals and guarded copies.'],['activity','Review approvals','Inspect exact actions and audience.']].map(([id,title,note])=><a href={'#'+id} key={id} className="n-shortcut"><h2>{title}<ArrowUpRight size={17}/></h2><p>{note}</p></a>)}</div>
 <details className="n-panel dashboard-help"><summary>How your archive, memory, and runtime fit together</summary><div className="n-explain-grid"><div><h3>Original sources</h3><p>Messages, files and revisions are preserved in your archive. Guarded copies are separate, editable versions.</p><a href="#archive">Inspect your archive →</a></div><div><h3>Working notes</h3><p>Hermes maintains compact generated notes and conversation history per profile. Verify claims against their source evidence.</p><a href="#memory">Read working notes →</a></div><div><h3>Long-term memory</h3><p>Honcho learns authorized sources with durable receipts and audience isolation. Connection and memory availability are shown separately.</p><a href="#honcho">Inspect memory availability →</a></div></div></details></div>;
}
