import {useRevisionDraft} from '../lib/draft';
import {React,sdk,h,useState,useEffect,useRef,useMemo,base,call,button,errorText,labels,Panel,Data,friendlyState,jobName,profileName,Details,RouteLink,Steps,download,exportJSON,useLoad,useResource,refreshResources,StatusBadge,Button,Badge,Alert,Progress,Table,Tabs,TabsList,TabsTrigger,TabsContent,Modal,Sheet,EmptyState} from '../lib/page-helpers.js';
export function Settings({notify}) {
 return h(Tabs,{defaultValue:'nocheh'},h(TabsList,{'aria-label':'Settings category'},h(TabsTrigger,{value:'nocheh'},'Nocheh settings'),h(TabsTrigger,{value:'hermes'},'Hermes preferences'),h(TabsTrigger,{value:'policy'},'Policy defaults')),
  h(TabsContent,{value:'nocheh',forceMount:true},h(NochehSettings,{notify})),h(TabsContent,{value:'hermes',forceMount:true},h(HermesPreferences,{notify})),h(TabsContent,{value:'policy',forceMount:true},h(PolicySettings,{notify})));
}
  function PolicySettings({notify}) {
    const [tick,setTick]=useState(0),[data,error]=useLoad('/policy',tick),[changes,setChanges,editRevision]=useRevisionDraft(data?.revision),[busy,setBusy]=useState(false);
    const save=async e=>{e.preventDefault();setBusy(true);try{await call('/policy',{changes,revision:editRevision});setChanges({});setTick(v=>v+1);notify('Global preferences saved. Profiles that inherit them use them on the next turn.');}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
    return h(Panel,{title:'Global preference defaults',note:'Profiles can inherit these values or keep an explicit override. Existing profile overrides are preserved.'},
      error&&h('p',{role:'alert'},error),!data&&!error&&h('p',{role:'status'},'Loading policy…'),data&&h('form',{onSubmit:save},h('div',{className:'n-form'},...Object.entries(data.schema).map(([key,spec])=>{
        const input={id:'policy-'+key,value:changes[key]??data.values[key],disabled:busy,onChange:e=>setChanges({...changes,[key]:spec.choices?e.target.value:Number(e.target.value)})};
        return h('div',{className:'n-field',key},h('label',{htmlFor:input.id},({'nocheh_tools.shell':'Controlled shell','nocheh_tools.browser':'Controlled browser','nocheh_tools.mcp':'Controlled MCP','agent.reasoning_effort':'Reasoning effort','agent.max_iterations':'Maximum agent steps','agent.run_budget_seconds':'Time per turn (seconds)','memory.memory_char_limit':'General memory limit (characters)','memory.user_char_limit':'User profile limit (characters)'})[key]||key),spec.choices?h('select',input,...spec.choices.map(v=>h('option',{value:v,key:v},v))):h('input',{...input,type:'number',min:spec.min,max:spec.max,required:true}),h('small',null,changes[key]===null?'Will use the built-in default after saving.':'Effective source: '+data.origins[key]),button('Use built-in default',()=>setChanges({...changes,[key]:null}),busy));
      })),h('div',{className:'n-actions'},h('button',{className:'n-primary',disabled:busy||!Object.keys(changes).length},busy?'Saving…':'Save global preferences'),button('Discard edits',()=>setChanges({}),busy))),
      h('p',{className:'n-muted'},'External actions currently require owner review. Broader tool policies become available with the tools phase; job overrides are stored for the scheduling phase.'));
  }
  function NochehSettings({notify}) {
    const [refresh,setRefresh]=useState(0),[data,error]=useLoad('/settings',refresh);
    const [changes,setChanges,editRevision]=useRevisionDraft(data?.revision),[busy,setBusy]=useState(false),[review,setReview]=useState(false);
    const save=async()=>{setBusy(true);try{await call('/settings',{revision:editRevision,changes});setChanges({});setReview(false);setRefresh(v=>v+1);notify('Nocheh settings saved. Apply saved settings when you are ready to update running services.');}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
    const apply=async()=>{setBusy(true);try{await call('/settings/apply',{});notify('Applying saved settings. Follow the result in Maintenance.');}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
    if(error&&!data)return h(Alert,null,'Settings are unavailable.');
    if(!data)return h('p',{role:'status'},'Loading settings…');
    const hints={TELEGRAM_ENABLED:'Start or stop Telegram message handling when settings are applied.',TELEGRAM_OWNER_ID:'Your numeric Telegram user ID. Only the owner can administer Nocheh.',TELEGRAM_GROUP_IDS:'Comma-separated numeric chat IDs. Each selected group uses its own memory and sources.',TELEGRAM_BOT_TOKEN:'The token from BotFather for the bot used by the native Hermes Telegram adapter.',NOCHEH_MODEL:'The model used through your ChatGPT subscription.',NOCHEH_GUARD_MODE:'On uses saved guarded copies for agents and memory. Off uses originals with the same access rules.',NOCHEH_GUARD_TRUSTED_ENDPOINTS:'Explicit destinations for trusted preparation services. This does not bypass guarding for agents.',NOCHEH_PORT:'Local port used by the archive service.'};
    const field=f=>{
      const value=changes[f.key]??f.value??'';
      const attrs={id:f.key,disabled:busy||!f.editable,value,type:f.secret?'password':'text',autoComplete:'off','aria-describedby':f.key+'-help',onChange:e=>{const next={...changes};if(f.secret&&!e.target.value)delete next[f.key];else next[f.key]=e.target.value;setChanges(next);setReview(false);}};
      const options=f.key==='NOCHEH_GUARD_MODE'?[['on','On · use guarded copies'],['off','Off · use originals']]:[['false','Disabled'],['true','Enabled']];
      return h('div',{className:'n-field',key:f.key},h('label',{htmlFor:f.key},labels[f.key]||f.key),
        f.key==='NOCHEH_GUARD_MODE'||f.key==='TELEGRAM_ENABLED'?h('select',attrs,...options.map(([value,label])=>h('option',{key:value,value},label))):h('input',attrs),
        h('small',{id:f.key+'-help'},hints[f.key],f.secret?' '+(f.configured?(f.editable?'Configured. Leave blank to keep it; enter a replacement to change it.':'Configured and managed internally.'):'Not configured.'):!f.editable?' Managed automatically.':''));
    };
    const group=(title,note,keys)=>h('fieldset',{className:'n-settings-group'},h('legend',null,title),h('p',{className:'n-muted'},note),h('div',{className:'n-form'},...data.fields.filter(f=>keys.includes(f.key)).map(field)));
    return h(Panel,{title:'Nocheh settings',note:'Telegram access, model routing and privacy for the whole installation. Stored in Nocheh’s .env file.'},
      error&&h(Alert,null,'Saved settings may be stale. Edits are retained.'),
      editRevision!==data.revision&&h(Alert,null,'These settings changed elsewhere. Your edits are retained against the original revision. Discard edits to load the new values, or attempt Save to see the conflict.'),
      h(StatusBadge,{state:data.apply_state,label:({current:'Saved settings match the last successful apply',pending:'Saved changes are waiting to be applied',unverified:'Running settings have not been verified by this dashboard'})[data.apply_state]||data.apply_state}),
      h(Steps,{items:['Edit and review','Save configuration','Apply to running services']}),
      h('form',{onSubmit:e=>{e.preventDefault();setReview(true);}},
        group('Telegram access','Choose who can use the assistant and which groups it can participate in.',['TELEGRAM_ENABLED','TELEGRAM_OWNER_ID','TELEGRAM_GROUP_IDS','TELEGRAM_BOT_TOKEN']),
        group('Model and privacy','These rules apply to outgoing model requests. Hermes profile preferences are in the other settings section.',['NOCHEH_MODEL','NOCHEH_GUARD_MODE']),
        h('details',{className:'n-advanced'},h('summary',null,'Advanced · destinations, connections and internal credentials'),h('div',{className:'n-form'},...data.fields.filter(f=>!['TELEGRAM_ENABLED','TELEGRAM_OWNER_ID','TELEGRAM_GROUP_IDS','TELEGRAM_BOT_TOKEN','NOCHEH_MODEL','NOCHEH_GUARD_MODE'].includes(f.key)).map(field))),
        h('div',{className:'n-actions'},h('button',{disabled:busy||!Object.keys(changes).length},'Review changes'),button('Discard edits',()=>{setChanges({});setReview(false);},busy||!Object.keys(changes).length))),
      review&&h('div',{className:'n-review'},h('h3',null,'Review before saving'),h('p',null,'Saving changes the configuration file. Running services update only after Apply.'),...Object.entries(changes).map(([k,v])=>h('p',{key:k},(labels[k]||k)+': '+(data.fields.find(f=>f.key===k)?.secret?'Replace stored credential':v||'(empty)'))),button('Save changes',save,busy,'n-primary')),
      h('div',{className:'n-apply'},h('h3',null,'Apply saved settings'),h('p',{className:'n-muted'},'Updates the running services and may briefly interrupt Telegram replies. Save or discard your current edits first.'),button('Apply saved settings',apply,busy||!!Object.keys(changes).length),h(RouteLink,{page:'operations'},'View apply results →')));
  }
  function HermesPreferences({notify}) {
    const [profiles,error]=useLoad('/memory/profiles'),[scope,setScope]=useState(''),[tick,setTick]=useState(0),[busy,setBusy]=useState(false);
    useEffect(()=>{if(!scope&&profiles?.profiles?.length)setScope(profiles.profiles[0].scope);},[profiles]);
    const [prefs,problem]=useLoad(scope?'/memory/preferences?scope='+encodeURIComponent(scope):null,tick);
    const [changes,setChanges,editRevision]=useRevisionDraft(prefs?.revision);
    const names={'nocheh_tools.shell':['Controlled shell','Propose commands in an isolated workspace. Each execution requires approval or an exact bounded permission.'],'nocheh_tools.browser':['Controlled browser','Inspect an approved public page offline. No logins or interactive actions.'],'nocheh_tools.mcp':['Controlled MCP','Propose an exact call to a public HTTPS MCP server. No ambient credentials.'],'agent.reasoning_effort':['Reasoning effort','Higher effort allows more reasoning and can take longer.'],'agent.max_iterations':['Maximum agent steps','Maximum tool and reasoning iterations in one turn.'],'agent.run_budget_seconds':['Time per turn (seconds)','Upper time budget for one assistant turn.'],'memory.memory_char_limit':['General memory limit (characters)','Space available for Hermes’s general memory note.'],'memory.user_char_limit':['User profile limit (characters)','Space available for Hermes’s user profile note.']};
    const save=async e=>{e.preventDefault();if(prefs?.scope!==scope)return;setBusy(true);try{await call('/memory/preferences',{scope,revision:editRevision,changes});setChanges({});setTick(v=>v+1);notify('Hermes preferences saved for this profile. They take effect on the next turn.');}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
    return h(Panel,{title:'Hermes preferences',note:'Agent behavior and memory limits for one chat profile. Saved in that profile’s Hermes config.yaml and used on its next turn; no service restart needed.'},
      error&&h('p',{role:'alert'},error),h('label',null,'Profile to configure',h('select',{value:scope,disabled:busy,onChange:e=>{setScope(e.target.value);setChanges({});}},...(profiles?.profiles||[]).map(p=>h('option',{value:p.scope,key:p.scope},profileName(p))))),
      !profiles&&!error&&h('p',{role:'status'},'Loading profiles…'),profiles&&!profiles.profiles.length&&h('p',null,'Configure the Telegram owner and groups in Nocheh settings to make profiles available.'),
      problem&&h('p',{role:'alert'},problem),scope&&!problem&&prefs?.scope!==scope&&h('p',{role:'status'},'Loading this profile’s preferences…'),
      scope&&prefs?.scope===scope&&h('form',{onSubmit:save},h('div',{className:'n-form n-preferences'},...Object.entries(prefs.schema).map(([key,spec])=>{
        const input={id:key,value:changes[key]??prefs.values[key],disabled:busy,'aria-describedby':key+'-help',onChange:e=>setChanges({...changes,[key]:spec.choices?e.target.value:Number(e.target.value)})};
        return h('div',{className:'n-field',key},h('label',{htmlFor:key},names[key]?.[0]||key),spec.choices?h('select',input,...spec.choices.map(v=>h('option',{key:v,value:v},v[0].toUpperCase()+v.slice(1)))):h('input',{...input,type:'number',min:spec.min,max:spec.max,required:true,step:1}),h('small',{id:key+'-help'},changes[key]===null?'Will inherit the global value after saving.':(names[key]?.[1]||'')+' Effective source: '+(prefs.origins?.[key]||'profile')),button('Inherit global value',()=>setChanges({...changes,[key]:null}),busy));
      })),h('div',{className:'n-actions'},h('button',{disabled:busy||!Object.keys(changes).length,className:'n-primary'},busy?'Saving…':'Save Hermes preferences'),button('Discard edits',()=>setChanges({}),busy||!Object.keys(changes).length))),
      h('p',{className:'n-muted n-afterword'},'Model routing, enabled tools and access policy are managed by Nocheh. These are the supported native preferences, not the full Hermes configuration.'),h(RouteLink,{page:'memory'},'Read this installation’s Hermes memory →'));
  }
