import {useDeferredValue,useId,useState} from 'react';
import {Alert,Badge,Button,Sheet} from './ui/primitives';
import {CursorButtons,Provenance,ResourceState} from '../lib/owner-controls';
import {useResource} from '../lib/resource';

export type Conversation={space_id:string;name:string|null;kind:string;parent_name?:string|null};
export type Directory={items:Conversation[];total:number;next_cursor:string|null;state:string;observed_at:string};
export function conversationName(row:Conversation){return row.name?.trim()||`${row.kind==='topic'?'Topic':'Conversation'} ${row.space_id}`;}
export function conversationLabel(row:Conversation){return `${conversationName(row)} · ${row.kind}${row.parent_name?' · '+row.parent_name:''} · ${row.space_id}`;}
/** Native selection and explicit search keep the complete directory keyboard accessible. */
export function ConversationSelector({label,value,onChange,multiple=false,disabled=false,description}:{label:string;value:string[];onChange:(ids:string[])=>void;multiple?:boolean;disabled?:boolean;description?:string}){
 const id=useId(),[query,setQuery]=useState(''),deferred=useDeferredValue(query),[pages,setPages]=useState(['']),[manual,setManual]=useState(''),[known,setKnown]=useState<Record<string,Conversation>>({});
 const resource=useResource<Directory>('/conversations?'+new URLSearchParams({q:deferred,after:pages.at(-1)!,limit:'40'})),rows=resource.data?.items??[];
 const pick=(space:string)=>{if(!space)return;const found=rows.find(row=>row.space_id===space);if(found)setKnown(current=>({...current,[space]:found}));onChange(multiple?[...new Set([...value,space])]:[space]);};
 return <div className="conversation-picker"><label htmlFor={id+'-search'}>{label}</label><input id={id+'-search'} type="search" value={query} placeholder="Search by conversation name or ID" disabled={disabled} onChange={event=>{setQuery(event.target.value);setPages(['']);}}/>
 <label className="sr-only" htmlFor={id+'-select'}>Choose {label.toLowerCase()}</label><select id={id+'-select'} value="" disabled={disabled||!!resource.error||!rows.length} onChange={event=>pick(event.target.value)}><option value="">{resource.loading&&!resource.data?'Loading conversations…':multiple?'Add a conversation…':'Choose a conversation…'}</option>{rows.map(row=><option key={row.space_id} value={row.space_id} disabled={value.includes(row.space_id)}>{conversationLabel(row)}</option>)}</select>
 <ResourceState {...resource} hasData={!!resource.data}/>{resource.data&&<small>{resource.data.total} matching conversations · exact chats and topics</small>}<CursorButtons pages={pages} next={resource.data?.next_cursor} onChange={setPages}/>
 {value.length>0&&<ul className="conversation-selected" aria-label={'Selected '+label.toLowerCase()}>{value.map(space=>{const row=rows.find(row=>row.space_id===space)??known[space];return <li key={space}><span><strong>{row?conversationName(row):'Conversation '+space}</strong><small>{row?`${row.kind} · `:''}{space}</small></span><Button size="sm" disabled={disabled} aria-label={'Remove '+(row?conversationName(row):space)} onClick={()=>onChange(value.filter(item=>item!==space))}>Remove</Button></li>;})}</ul>}
 {description&&<small>{description}</small>}<details><summary>Use an exact conversation ID</summary><div className="search-toolbar"><label className="n-grow">Conversation ID<input value={manual} disabled={disabled} onChange={event=>setManual(event.target.value)} placeholder="-10042 or -10042/topic/7"/></label><Button disabled={disabled||!manual.trim()} onClick={()=>{pick(manual.trim());setManual('');}}>Use ID</Button></div><small>Use this when a conversation has no stored name. This does not discover conversations or change access.</small></details></div>;
}
export function ConversationContext({space,onClose,returnFocus}:{space:string|null;onClose:()=>void;returnFocus?:HTMLElement|null}){
 const data=useResource<any>(space?'/conversations/context?space='+encodeURIComponent(space):null),context=data.data;
 return <Sheet open={!!space} onOpenChange={open=>{if(!open)onClose();}} title={context?.conversation?conversationName(context.conversation):'Conversation context'} description="Organization, knowledge, and action permissions are separate." returnFocus={returnFocus}>
 <ResourceState {...data} hasData={!!context}/>{context&&<div className="conversation-context"><p className="owner-identifier">{space}</p>{context.state==='partial'&&<Alert>Some authorities are unavailable. Missing observations are not a denial or permission.</Alert>}
 <section className="context-authority"><h3>Who may address Nocheh</h3>{context.addressing?.state==='unavailable'?<Alert>Participant permissions are unavailable.</Alert>:<><p>{context.addressing?.enabled?'Telegram is enabled.':'Telegram is disabled.'} {context.conversation?.kind==='private'?'Only the configured owner may use owner-private controls.':context.addressing?.group_enabled?'This group is enabled; explicit member grants and denials apply.':'This group is not enabled.'}</p><p>{context.addressing?.granted?.length??0} explicit grants · {context.addressing?.denied?.length??0} explicit denials</p></>}<Provenance value={context.addressing} label="Exact participant controls"/></section>
 <section className="context-authority"><h3>Knowledge this conversation may use</h3><p>{context.knowledge_access?.note}</p><p>{context.knowledge_access?.owner_access?'Owner access to permitted knowledge.':'Own permitted sources plus explicitly shared knowledge.'}</p><p>{context.knowledge_access?.sharing_rules?.length??0} sharing rules · {context.knowledge_access?.fact_grants?.length??0} fact grants</p><Provenance value={context.knowledge_access} label="Exact sources, rules and grants"/></section>
 <section className="context-authority"><h3>External actions Nocheh may perform</h3><p>{context.external_actions?.note}</p><p>{context.external_actions?.permissions?.length??0} recorded action permissions. Execution and delivery require their own confirmed results.</p><Provenance value={context.external_actions} label="Exact action policy and permissions"/></section>
 <section className="context-authority"><h3>Project organization</h3><p>{context.organization?.effective?.project?.name??'No effective project'}{context.organization?.effective?.inherited?' · inherited from group':''}</p><p>{context.organization?.note}</p><Provenance value={context.organization} label="Assignment and organization authority"/></section>
 {context.memory&&<section className="context-authority"><h3>Memory availability</h3><Badge>{context.memory.availability}</Badge><p>{context.memory.note}</p></section>}<p className="n-muted">Project membership organizes understanding. It does not grant knowledge access or permission to act.</p><small>Observed {new Date(context.observed_at).toLocaleString()}</small></div>}</Sheet>;
}
