import {useEffect,useRef,useState} from 'react';
import {Alert,Badge,Button,EmptyState,Sheet} from './ui/primitives';
import {CursorButtons,EvidenceLinks,Provenance,ResourceState,useOwnerCommand} from '../lib/owner-controls';
import {refreshResources,useResource} from '../lib/resource';
import {decisionLabels,decisionLink,knowledgeDecisionControls,proposalState,selectedDecision,type Decision,type DecisionKind,type DecisionPage} from '../lib/supervision';
import {RequestRow} from '../pages/memory-map';
import {SuggestionRow} from '../pages/entities';

export type KnowledgeProposal={id:string;kind:string;state:string;revision:number;created_at:string;source_scope:string;source_reference?:{id:string};proposal:any;result?:any;decision_history?:unknown[];error_code?:string;delegation_id?:string;delegation_revision?:number;affected_topics?:Record<string,string[]>};
const effects:Record<string,string>={project_save:'Save this project name, description and status. Archiving keeps its history.',project_assignment:'Change this conversation’s project context. This does not share knowledge.',entity_rename:'Change the displayed name of this identity.',entity_correct:'Replace the active interpretation with this owner correction while retaining its history.',entity_merge:'Link these identities. Review the evidence that they refer to the same person.',entity_unmerge:'Undo this identity link and retain the earlier decision history.',sharing_rule:'Change the exact sources, destination and sharing instructions. Enabling a filtered rule permits automatic filtered sharing.',fact_grant:'Allow this exact conversation to use the approved fact wording under the specified duration.',fact_revoke:'Stop future recall through this grant. Previously delivered messages remain delivered.'};
const fieldLabels:Record<string,string>={name:'Name',description:'Description',state:'Status',space_id:'Conversation',project_id:'Project',mode:'Mode',target_id:'Target identity',content:'Exact corrected knowledge',attribution:'Attribution',uncertainty:'Certainty',retired:'Retire this knowledge',sources:'Source conversations',destination:'Destination',instructions:'Privacy instructions',enabled:'Enabled',wording:'Exact wording to share',fact_id:'Fact',fact_revision:'Fact revision'};
function ExactEffect({proposal}:{proposal:any}){const payload=proposal?.payload??{};return <><h3>{String(proposal?.kind??'Knowledge change').replaceAll('_',' ')}</h3><p>{effects[proposal?.kind]??'Apply this exact prepared change.'}</p><dl className="proposal-fields">{Object.entries(payload).filter(([key])=>fieldLabels[key]).map(([key,value])=><div key={key}><dt>{fieldLabels[key]}</dt><dd dir="auto">{Array.isArray(value)?value.join(', '):typeof value==='boolean'?value?'Yes':'No':String(value??'None')}</dd></div>)}</dl><p className="n-muted">Approval applies only this exact change. Recorded revision and wording checks still apply.</p></>;}
export function KnowledgeReview({item,disabled=false,stale=false,onChanged=()=>{}}:{item:KnowledgeProposal;disabled?:boolean;stale?:boolean;onChanged?:()=>void}){
 const [base]=useState(item),command=useOwnerCommand(),changed=base.revision!==item.revision,proposal=base.proposal;
 const controls=knowledgeDecisionControls(base.state,{unavailable:disabled,changed,busy:command.busy,stale});
 const save=async(decision:string)=>{if(await command.run('/knowledge/proposals/'+base.id+'/decide',{decision,expected_revision:base.revision}))onChanged();};
 return <div className="owner-form knowledge-review"><Badge>{proposalState(item.state)}</Badge><p>{proposal?.reason||'Review the exact proposed changes and their evidence.'}</p>
 {proposal?.kind==='organization'?<><h3>Proposed organization</h3>{proposal.creates?.map((create:any)=><article className="context-authority" key={create.key}><strong>Create project: {create.name}</strong><p>{create.description}</p><EvidenceLinks sources={(create.evidence_ids??[]).map((id:string)=>({id}))}/></article>)}{proposal.assignments?.map((assignment:any)=><article className="context-authority" key={assignment.space_id}><strong>Assign conversation {assignment.space_id}</strong><p>Project {assignment.project_id??proposal.creates?.find((create:any)=>create.key===assignment.project_key)?.name??assignment.project_key}</p><p>{assignment.reason}</p><EvidenceLinks sources={(assignment.evidence_ids??[]).map((id:string)=>({id}))}/></article>)}<p className="n-muted">These changes organize knowledge. They do not change who can address Nocheh, share knowledge, or authorize external actions.</p></>:<ExactEffect proposal={proposal}/>}
 {base.affected_topics&&Object.values(base.affected_topics).some(topics=>topics.length>0)&&<section className="context-authority"><h3>Inherited topic consequences</h3><p>These existing topics will inherit the changed group assignment, in addition to the direct assignments above.</p>{Object.entries(base.affected_topics).filter(([,topics])=>topics.length>0).map(([group,topics])=><div key={group}><strong className="owner-identifier">Group {group}</strong><ul>{topics.map(topic=><li className="owner-identifier" key={topic}>{topic}</li>)}</ul></div>)}<p className="n-muted">This is the exact topic set prepared for review. A newly discovered inheriting topic requires a fresh proposal.</p></section>}
 <p>Prepared from conversation <span className="owner-identifier">{base.source_scope}</span>.</p>{base.source_reference?.id&&<EvidenceLinks sources={[base.source_reference]}/>}{base.delegation_id&&<p>Delegated authority revision {base.delegation_revision}. The saved authority is rechecked before application.</p>}
 <Provenance value={{proposal:base.proposal,authorization:{delegation_id:base.delegation_id,delegation_revision:base.delegation_revision},result:base.result,decision_history:base.decision_history}} label="Exact changes, authority, before and after, and receipt"/>
 {base.error_code&&<Alert>{base.error_code.replaceAll('_',' ')}</Alert>}{changed&&<Alert>The proposal changed. Close and reopen it before deciding; this review has been retained.</Alert>}{command.error&&<Alert>{command.error}</Alert>}
 {base.state==='review'&&<div className="n-actions"><Button variant="default" disabled={!controls.approve} onClick={()=>void save('approve')}>{command.busy?'Saving…':'Approve exact changes'}</Button><Button disabled={!controls.reject} onClick={()=>void save('reject')}>Reject</Button></div>}
 {['queued','waiting'].includes(base.state)&&<><p className="n-muted">Authorization was recorded. Application is still pending and has its own receipt.</p><Button disabled={!controls.cancel} onClick={()=>void save('cancel')}>Cancel pending change</Button></>}
 {['stale','failed'].includes(base.state)&&<><p className="n-muted">Dismiss this proposal from the decision inbox. Its recorded outcome and decision history remain available. Applying a corrected change requires a fresh proposal.</p><Button disabled={!controls.cancel} onClick={()=>void save('cancel')}>{command.busy?'Dismissing…':'Dismiss proposal'}</Button></>}
 {base.state==='applied'&&base.kind==='organization'&&<><p className="n-muted">Undo checks the current revisions and preserves the original receipt. It will not overwrite later owner changes.</p><Button disabled={!controls.undo} onClick={async()=>{if(await command.run('/knowledge/proposals/'+base.id+'/undo',{expected_revision:base.revision}))onChanged();}}>Undo organization</Button></>}
 </div>;
}
export function Decisions({onAction,notify}:{onAction:(action:any,element:HTMLElement)=>void;notify:(message:string,error?:boolean)=>void}){
 const [kind,setKind]=useState(''),[pages,setPages]=useState(['']),[selected,setSelected]=useState(()=>selectedDecision(location.hash)),trigger=useRef<HTMLElement|null>(null);
 const data=useResource<DecisionPage>('/decisions?'+new URLSearchParams({kind,after:pages.at(-1)!,limit:'30'}),10000),detail=useResource<Decision>(selected?'/decisions/'+selected.kind+'/'+encodeURIComponent(selected.id):null,10000);
 useEffect(()=>{const changed=()=>setSelected(selectedDecision(location.hash));addEventListener('hashchange',changed);return()=>removeEventListener('hashchange',changed);},[]);
 const open=(item:Decision,element:HTMLElement)=>{trigger.current=element;setSelected({kind:item.kind,id:item.id});history.replaceState(null,'',decisionLink(item.kind,item.id));};
 const close=()=>{setSelected(null);if(selectedDecision(location.hash))history.replaceState(null,'','#activity');};
 const changed=()=>{notify('Decision saved. Application and delivery are tracked separately.');close();};
 useEffect(()=>{const item=detail.data;if(!selected||detail.error||item?.observation==='stale'||item?.id!==selected.id||!item?.detail||!['controlled_action','telegram_action'].includes(item.kind))return;
  setSelected(null);onAction(item.detail,trigger.current??document.querySelector<HTMLElement>('h1')??document.body);
 },[selected,detail.data,detail.error,onAction]);
 return <><section className="n-panel"><div className="list-heading"><div><p className="archive-kicker">Your decision needed</p><h2>Decisions {data.data&&<Badge>{data.data.total}</Badge>}</h2><p className="n-muted">Review exact actions, knowledge access, identity suggestions, and organization changes in one place.</p></div><Button onClick={()=>void refreshResources()}>Refresh decisions</Button></div>
 <label className="decision-filter">Show<select value={kind} onChange={event=>{setKind(event.target.value);setPages(['']);}}><option value="">All decisions</option>{Object.entries(decisionLabels).map(([value,label])=><option key={value} value={value}>{label}{data.data?.totals[value]!==undefined?' ('+data.data.totals[value]+')':''}</option>)}</select></label>
 <ResourceState {...data} hasData={!!data.data}/>{data.data?.state==='partial'&&<Alert>Some decision sources are unavailable. This is a partial list.</Alert>}{data.data&&data.data.state==='current'&&!data.error&&data.data.total===0&&<EmptyState title="Nothing needs your decision">Automatic work is recorded in history. New exceptions appear here.</EmptyState>}
 <div className="owner-records decision-records">{data.data?.items.map(item=><article key={item.kind+':'+item.id}><div className="list-heading"><div><small>{decisionLabels[item.kind]}</small><h3>{item.title}</h3></div><Badge>{item.state.replaceAll('_',' ')}</Badge></div>{item.summary&&<p>{item.summary}</p>}{item.destination&&<p>Destination <span className="owner-identifier">{item.destination}</span></p>}<small>{new Date(item.created_at).toLocaleString()}</small><div className="n-actions"><Button disabled={!!data.error} variant="default" onClick={event=>open(item,event.currentTarget)}>Review and decide</Button></div></article>)}</div><CursorButtons pages={pages} next={data.data?.next_cursor} onChange={setPages}/></section>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)close();}} title={detail.data?.title??'Review decision'} description="Inspect the exact effect and evidence before deciding." returnFocus={trigger.current}><ResourceState {...detail} hasData={!!detail.data}/>{detail.data?.observation==='stale'&&<Alert>The proposal dependencies changed. This observation cannot authorize applying the change.</Alert>}{detail.data&&<DecisionReview key={detail.data.kind+':'+detail.data.id} item={detail.data} disabled={!!detail.error} onChanged={changed} onAction={(action,element)=>{close();onAction(action,trigger.current??element);}}/>}</Sheet></>;
}
function DecisionReview({item,disabled,onChanged,onAction}:{item:Decision;disabled:boolean;onChanged:()=>void;onAction:(action:any,element:HTMLElement)=>void}){
 const [record]=useState(item.detail),changed=record?.revision!==item.detail?.revision||record?.state!==item.detail?.state||record?.status!==item.detail?.status||record?.fingerprint!==item.detail?.fingerprint;
 disabled=disabled||changed;const stale=item.observation==='stale';
 const notice=changed?<Alert>This decision changed while you were reviewing it. Your draft is retained below. Close and reopen it to review the latest version before submitting.</Alert>:null;
 if(!record)return <Alert>The complete decision could not be loaded. No decision can be submitted from this partial record.</Alert>;
 if(item.kind==='memory_access')return <>{notice}<RequestRow item={record} disabled={disabled||stale} onChanged={onChanged}/></>;
 if(item.kind==='entity')return <>{notice}{record.status==='pending'||record.state==='pending'||item.state==='pending'?<SuggestionRow item={record} disabled={disabled||stale} onChanged={onChanged}/>:<><Badge>{item.state}</Badge><Provenance value={record} label="Saved identity decision"/></>}</>;
 if(item.kind==='knowledge')return <>{notice}<KnowledgeReview item={record} disabled={disabled} stale={stale} onChanged={onChanged}/></>;
 return <div className="owner-form">{notice}<p>{item.summary||'Review the exact operation, scope and destination.'}</p><pre className="n-data" dir="auto">{JSON.stringify(record.arguments,null,2)}</pre><p>Destination or scope: {record.scope}</p><Badge>{record.state}</Badge><Button variant="default" disabled={disabled||stale} onClick={event=>onAction(record,event.currentTarget)}>Open exact action review</Button></div>;
}
