import {useState} from 'react';
import {Alert,Badge,Button,EmptyState,Sheet} from './ui/primitives';
import {ConversationSelector} from './conversations';
import {KnowledgeReview,type KnowledgeProposal} from './decisions';
import {CursorButtons,Provenance,ResourceState,useOwnerCommand} from '../lib/owner-controls';
import {proposalState} from '../lib/supervision';
import {useResource} from '../lib/resource';

type Project={id:string;name:string;state:string};
type Delegation={id:string;name:string;enabled:boolean;scopes:string[];project_ids:string[];allow_create:boolean;expires_at:string|null;revision:number;suspended_scopes?:string[];expired?:boolean};
export function ProjectSelector({value,onChange,multiple=false,disabled=false}:{value:string[];onChange:(ids:string[])=>void;multiple?:boolean;disabled?:boolean}){
 const [pages,setPages]=useState(['']),data=useResource<{projects:Project[];next:string|null}>('/projects?after='+encodeURIComponent(pages.at(-1)!)),[names,setNames]=useState<Record<string,string>>({});
 const choices=data.data?.projects??[];
 return <div className="conversation-picker"><label>Permitted project{multiple?'s':''}<select value="" disabled={disabled||!!data.error} onChange={event=>{const id=event.target.value;if(!id)return;setNames(current=>({...current,[id]:choices.find(project=>project.id===id)?.name??id}));onChange(multiple?[...new Set([...value,id])]:[id]);}}><option value="">{multiple?'Add a project…':'Choose a project…'}</option>{choices.map(project=><option key={project.id} value={project.id} disabled={project.state!=='active'||value.includes(project.id)}>{project.name} · {project.id}{project.state!=='active'?' (archived)':''}</option>)}</select></label><ResourceState {...data} hasData={!!data.data}/><CursorButtons pages={pages} next={data.data?.next} onChange={setPages}/><ul className="conversation-selected">{value.map(id=><li key={id}><span><strong>{choices.find(project=>project.id===id)?.name??names[id]??'Project'}</strong><small>{id}</small></span><Button size="sm" disabled={disabled} onClick={()=>onChange(value.filter(value=>value!==id))}>Remove</Button></li>)}</ul></div>;
}
function DelegationEditor({item,onSaved}:{item:Delegation|null;onSaved:()=>void}){
 const [name,setName]=useState(item?.name??''),[scopes,setScopes]=useState(item?.scopes??[]),[projects,setProjects]=useState(item?.project_ids??[]),[enabled,setEnabled]=useState(item?.enabled??false),[create,setCreate]=useState(item?.allow_create??false),[expires,setExpires]=useState(item?.expires_at?new Date(Date.parse(item.expires_at)-new Date(item.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):''),[resume,setResume]=useState(false),command=useOwnerCommand();
 const suspended=item?.suspended_scopes??[];
 return <form className="owner-form" onSubmit={event=>{event.preventDefault();void command.run('/organization/delegations',{...(item?{id:item.id}:{}),name,scopes,project_ids:projects,enabled,allow_create:create,resume_scopes:resume?suspended.filter(scope=>scopes.includes(scope)):[],expires_at:expires?new Date(expires).toISOString():null,expected_revision:item?.revision??0}).then(result=>{if(result)onSaved();});}}>
 <label>Permission name<input value={name} onChange={event=>setName(event.target.value)} maxLength={200} required disabled={command.busy}/></label><ConversationSelector label="Conversations the agent may organize" value={scopes} onChange={setScopes} multiple disabled={command.busy} description="Exact scopes only. A group selection does not include new or unselected topics."/>
 <ProjectSelector value={projects} onChange={setProjects} multiple disabled={command.busy}/><label className="owner-check"><input type="checkbox" checked={create} onChange={event=>setCreate(event.target.checked)} disabled={command.busy}/>Allow evidence-backed creation of new projects</label>
 <label>Expires at (optional)<input type="datetime-local" value={expires} onChange={event=>setExpires(event.target.value)} disabled={command.busy}/><small>Leave empty for permission until revoked.</small></label><label className="owner-check"><input type="checkbox" checked={enabled} onChange={event=>setEnabled(event.target.checked)} disabled={command.busy}/>Enable automatic organization within this scope</label>
 {suspended.length>0&&<div className="context-authority"><p>Owner changes suspended automatic organization for {suspended.length} conversation{suspended.length===1?'':'s'}.</p><ul>{suspended.map(scope=><li className="owner-identifier" key={scope}>{scope}</li>)}</ul><label className="owner-check"><input type="checkbox" checked={resume} onChange={event=>setResume(event.target.checked)} disabled={command.busy}/>Resume these conversations from their current assignments when saving (optional)</label></div>}
 <p className="n-muted">Automatic changes can only create projects and assign conversations. Identity, corrections, sharing, and fact access still require exact review. New permission applies to future capture; it does not authorize historical backfill.</p>{command.error&&<Alert>{command.error}</Alert>}<Button variant="default" type="submit" disabled={command.busy||!name.trim()||!scopes.length}>{command.busy?'Saving…':enabled?'Save organization permission':'Save disabled permission'}</Button>
 </form>;
}
export function Organization(){
 const [pages,setPages]=useState(['']),[historyPages,setHistoryPages]=useState(['']),[editor,setEditor]=useState<Delegation|'new'|null>(null),[selected,setSelected]=useState<string|null>(null),[trigger,setTrigger]=useState<HTMLElement|null>(null),command=useOwnerCommand();
 const delegations=useResource<{delegations:Delegation[];next:string|null}>('/organization/delegations?after='+encodeURIComponent(pages.at(-1)!)),history=useResource<{proposals:KnowledgeProposal[];next:string|null}>('/knowledge/proposals?after='+encodeURIComponent(historyPages.at(-1)!)),detail=useResource<KnowledgeProposal>(selected?'/knowledge/proposals/'+selected:null);
 return <><section className="n-panel"><div className="list-heading"><div><h2>Agent organization</h2><p className="n-muted">Let Nocheh maintain projects within a scope you choose. Automatic organization starts disabled.</p></div><Button variant="default" onClick={event=>{setTrigger(event.currentTarget);setEditor('new');}}>New permission</Button></div><ResourceState {...delegations} hasData={!!delegations.data}/>{command.error&&<Alert>{command.error}</Alert>}{delegations.data&&!delegations.data.delegations.length&&<EmptyState title="Automatic organization is not delegated">The agent can prepare suggestions. Choose exact conversations and projects to let it organize automatically.</EmptyState>}
 <div className="owner-records">{delegations.data?.delegations.map(item=><article key={item.id}><div className="list-heading"><h3>{item.name}</h3><Badge>{item.expired?'Expired':!item.enabled?'Disabled':item.suspended_scopes?.length?'Partly suspended':'Enabled'}</Badge></div><p>{item.scopes.length} conversations · {item.project_ids.length} existing projects{item.allow_create?' · May create new projects':''}</p><p>{item.expires_at?'Expires '+new Date(item.expires_at).toLocaleString():'Until revoked'}</p>{!!item.suspended_scopes?.length&&<p className="n-muted">Owner corrections suspended {item.suspended_scopes.length} conversation scopes. Explicitly resume them in the permission editor.</p>}<div className="n-actions"><Button onClick={event=>{setTrigger(event.currentTarget);setEditor(item);}}>Review scope</Button>{item.enabled&&<Button disabled={command.busy||!!delegations.error} onClick={()=>void command.run('/organization/delegations',{id:item.id,name:item.name,enabled:false,scopes:item.scopes,project_ids:item.project_ids,allow_create:item.allow_create,expires_at:item.expired?null:item.expires_at,expected_revision:item.revision})}>Disable permission</Button>}</div><Provenance value={item} label="Exact scope, watermark and assignment revisions"/></article>)}</div><CursorButtons pages={pages} next={delegations.data?.next} onChange={setPages}/></section>
 <section className="n-panel"><h2>Organization and knowledge history</h2><p className="n-muted">Prepared, waiting, applied, and unsuccessful work retain separate outcomes and evidence.</p><ResourceState {...history} hasData={!!history.data}/>{history.data&&!history.data.proposals.length&&<EmptyState title="No recorded knowledge changes">Agent proposals and their confirmed results will appear here.</EmptyState>}<div className="owner-records">{history.data?.proposals.map(item=><article key={item.id}><div className="list-heading"><h3>{item.proposal?.reason||item.kind.replaceAll('_',' ')}</h3><Badge>{proposalState(item.state)}</Badge></div><small>{new Date(item.created_at).toLocaleString()}</small><div className="n-actions"><Button onClick={event=>{setTrigger(event.currentTarget);setSelected(item.id);}}>Inspect change and receipt</Button></div></article>)}</div><CursorButtons pages={historyPages} next={history.data?.next} onChange={setHistoryPages}/></section>
 <Sheet open={!!editor} onOpenChange={open=>{if(!open)setEditor(null);}} title={editor==='new'?'Delegate project organization':'Review organization permission'} returnFocus={trigger}>{editor&&<DelegationEditor key={editor==='new'?'new':editor.id} item={editor==='new'?null:editor} onSaved={()=>setEditor(null)}/>}</Sheet>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}} title="Knowledge change" returnFocus={trigger}><ResourceState {...detail} hasData={!!detail.data}/>{detail.data&&<KnowledgeReview key={detail.data.id} item={detail.data} disabled={!!detail.error} onChanged={()=>setSelected(null)}/>}</Sheet></>;
}
