import {Badge,Button,EmptyState} from './ui/primitives';
import {EvidenceLinks,ResourceState} from '../lib/owner-controls';
import {useResource} from '../lib/resource';
import {decisionLink,type Decision} from '../lib/supervision';
import {conversationName,type Conversation} from './conversations';
export function ProjectContext({id,onConversation}:{id:string;onConversation:(space:string,element:HTMLElement)=>void}){
 const data=useResource<any>('/projects/'+encodeURIComponent(id)+'/context'),context=data.data;
 return <><ResourceState {...data} hasData={!!context}/>{context&&<div className="owner-form"><div><h3>{context.project.name}</h3><p>{context.project.description}</p><Badge>{context.project.state}</Badge></div>
 <section><h3>Related conversations</h3>{!context.conversations.length&&<EmptyState title="No assigned conversations">Assign conversations or delegate organization to the agent.</EmptyState>}<ul className="conversation-selected">{context.conversations.map((conversation:Conversation&{effective:any})=><li key={conversation.space_id}><span><strong>{conversationName(conversation)}</strong><small>{conversation.kind} · {conversation.space_id}</small><small>{conversation.effective.inherited?'Inherits from group':'Explicit assignment'}</small></span><Button onClick={event=>onConversation(conversation.space_id,event.currentTarget)}>Inspect context</Button></li>)}</ul></section>
 <section><div className="list-heading"><h3>Project knowledge</h3><Badge>{context.knowledge.total}</Badge></div>{!context.knowledge.items.length&&<p className="n-muted">No current project facts or guidance have been learned.</p>}<div className="owner-records">{context.knowledge.items.map((item:any)=><article key={(item.type??'learned')+':'+item.id}><div className="list-heading"><h4>{item.subject}</h4><Badge>{item.type==='claim'?'Project fact':'Learned guidance'}</Badge></div>{item.type==='claim'&&<><p className="memory-prose" dir="auto">{item.content}</p><small>{item.attribution} · {item.uncertainty} · revision {item.revision}</small><EvidenceLinks sources={item.evidence??[]}/></>}<a href={item.href??('#memory?view=learned&project='+encodeURIComponent(id)+'&entry='+encodeURIComponent(item.id))}>{item.type==='claim'?'Inspect relationships and corrections':'Read project guidance'} →</a></article>)}</div>{context.knowledge.next_cursor&&<p className="n-muted">Showing the first {context.knowledge.items.length} of {context.knowledge.total} records.</p>}<a href={'#memory?view=learned&project='+encodeURIComponent(id)}>Browse project guidance →</a></section>
 <section><div className="list-heading"><h3>Relevant decisions</h3><Badge>{context.decisions.total}</Badge></div>{!context.decisions.items.length&&<p className="n-muted">No current decisions for these conversations.</p>}<ul>{context.decisions.items.map((item:Decision)=><li key={item.kind+item.id}><a href={decisionLink(item.kind,item.id)}>{item.title}</a> · {item.state.replaceAll('_',' ')}</li>)}</ul>{context.decisions.next_cursor&&<p className="n-muted">Showing the first {context.decisions.items.length} of {context.decisions.total} decisions. <a href="#activity">Open the complete inbox</a>.</p>}</section>
 <p className="n-muted">Organization does not share chat content. Each conversation retains its own authorities.</p></div>}</>;
}
