import {ResponsiveContainer,LineChart,Line,BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,Legend} from 'recharts';
import {Table} from './ui/primitives';
export type MetricBucket={start:string;end:string;admitted:number;completed:number;terminal_failed:number;completion_ms_p50:number|null;completion_ms_p95:number|null;completion_samples:number};
export type Metrics={range:'24h'|'7d';family:string|null;from:string;to:string;observed_at:string;bucket_seconds:number;buckets:MetricBucket[]};
export const families:Record<string,string>={preparation:'Source preparation',telegram:'Telegram',imports:'Imports',memory_review:'Memory review',honcho:'Honcho',browser:'Browser turns',schedules:'Schedules',actions:'Approved messages',tools:'Controlled tools'};
const chartStyle={background:'var(--n-panel)',border:'1px solid var(--n-line)',borderRadius:8,color:'var(--n-text)',fontSize:12};
export const duration=(ms:number|null)=>ms===null?'—':ms<1000?Math.round(ms)+' ms':ms<60000?(ms/1000).toFixed(1)+' s':ms<3600000?(ms/60000).toFixed(1)+' min':(ms/3600000).toFixed(1)+' h';
const fullTime=(v:string)=>new Date(v).toLocaleString();
export default function WorkflowCharts({metrics,compact=false,counts=null}:{metrics:Metrics;compact?:boolean;counts?:{family:string;state:string;count:number}[]|null}){
 const data=metrics.buckets,format=(v:string)=>new Date(v).toLocaleString(undefined,metrics.range==='24h'?{hour:'numeric',minute:'2-digit'}:{month:'short',day:'numeric',hour:'numeric'});
 const workload=Object.entries(families).map(([family,name])=>{
  const count=(states:string[])=>(counts||[]).filter(c=>c.family===family&&states.includes(c.state)).reduce((n,c)=>n+c.count,0);
  return {name,running:count(['running']),waiting:count(['waiting','queued']),failed:count(['failed','retryable_failed']),uncertain:count(['ambiguous'])};
 });
 const grid=<CartesianGrid stroke="var(--n-line)" vertical={false}/>;
 const x=<XAxis dataKey="start" tickFormatter={format} tick={{fill:'var(--n-muted)',fontSize:10}} tickLine={false} axisLine={false} minTickGap={45}/>;
 const y=<YAxis allowDecimals={false} tick={{fill:'var(--n-muted)',fontSize:10}} tickLine={false} axisLine={false} width={34}/>;
 const tips=<Tooltip contentStyle={chartStyle} labelFormatter={v=>fullTime(String(v))}/>;
 const hasActivity=data.some(b=>b.admitted||b.completed||b.terminal_failed);
 return <><div className="chart-grid"><section className="chart-panel chart-wide"><div className="chart-title"><h3>Workflow activity</h3><span>Admissions and confirmed completions</span></div><div className="chart-canvas" role="group" aria-label="Workflow activity chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} accessibilityLayer margin={{top:12,right:10,bottom:0,left:0}}>{grid}{x}{y}{tips}<Legend iconType="line"/><Line type="linear" dataKey="admitted" name="Admitted" stroke="var(--n-active)" strokeWidth={2} dot={false} isAnimationActive={false}/><Line type="linear" dataKey="completed" name="Confirmed complete" stroke="var(--n-success)" strokeWidth={2} strokeDasharray="5 3" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>{!hasActivity&&<p className="chart-note">No workflow activity recorded in this period. Observed counts are zero.</p>}</section>
 {!compact&&<><section className="chart-panel"><div className="chart-title"><h3>Confirmed outcomes</h3><span>Recorded completions and terminal failures</span></div><div className="chart-canvas" role="group" aria-label="Confirmed workflow outcomes chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} accessibilityLayer>{grid}{x}{y}{tips}<Legend/><Bar dataKey="completed" name="Completed" fill="var(--n-success)" radius={[3,3,0,0]} isAnimationActive={false}/><Bar dataKey="terminal_failed" name="Terminal failure" fill="var(--n-danger)" radius={[3,3,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="chart-note">Retryable failures and uncertain effects remain separate in current status.</p></section>
 <section className="chart-panel"><div className="chart-title"><h3>Time to confirmed completion</h3><span>Includes waiting and retries · p50 / p95</span></div><div className="chart-canvas" role="group" aria-label="Workflow completion duration chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} accessibilityLayer>{grid}{x}<YAxis tickFormatter={duration} tick={{fill:'var(--n-muted)',fontSize:10}} tickLine={false} axisLine={false} width={58}/><Tooltip contentStyle={chartStyle} labelFormatter={(v,payload)=>fullTime(String(v))+(payload?.[0]?.payload?' · '+payload[0].payload.completion_samples+' samples':'')} formatter={(value:any)=>duration(value==null?null:Number(value))}/><Legend iconType="line"/><Line dataKey="completion_ms_p50" name="p50 duration" stroke="var(--n-accent)" strokeWidth={2} dot={{r:2}} connectNulls={false} isAnimationActive={false}/><Line dataKey="completion_ms_p95" name="p95 duration" stroke="var(--n-active)" strokeWidth={2} strokeDasharray="4 4" dot={{r:2}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>{!data.some(b=>b.completion_samples>0)&&<p className="chart-note">No confirmed completion samples in this period. Duration is unavailable.</p>}</section>
 <section className="chart-panel chart-wide"><div className="chart-title"><h3>Current workload by family</h3><span>Current observations · all families</span></div>{!counts?<p className="chart-note" role="status">Current workload is unavailable. Counts cannot be inferred.</p>:<div className="chart-canvas workload-chart" role="group" aria-label="Current workflow workload by family"><ResponsiveContainer width="100%" height="100%"><BarChart data={workload} layout="vertical" accessibilityLayer margin={{right:12}}><CartesianGrid stroke="var(--n-line)" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{fill:'var(--n-muted)',fontSize:10}}/><YAxis type="category" dataKey="name" width={120} tick={{fill:'var(--n-muted)',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={chartStyle}/><Legend/>{[['running','Running','--n-active'],['waiting','Waiting','--n-warning'],['failed','Failed','--n-danger'],['uncertain','Uncertain','--n-muted']].map(([key,label,color])=><Bar key={key} dataKey={key} name={label} fill={`var(${color})`} stackId="current" isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div>}</section></>}
 </div><details className="chart-data"><summary>View chart data</summary><Table aria-label="Workflow historical metrics"><thead><tr><th>Interval start</th><th>Interval end (exclusive)</th><th>Admitted</th><th>Completed</th><th>Terminal failures</th><th>p50 duration</th><th>p95 duration</th><th>Samples</th></tr></thead><tbody>{data.map(row=><tr key={row.start}><td><time dateTime={row.start} title={'Until '+fullTime(row.end)}>{fullTime(row.start)}</time></td><td><time dateTime={row.end}>{fullTime(row.end)}</time></td><td>{row.admitted}</td><td>{row.completed}</td><td>{row.terminal_failed}</td><td>{duration(row.completion_ms_p50)}</td><td>{duration(row.completion_ms_p95)}</td><td>{row.completion_samples}</td></tr>)}</tbody></Table>{!compact&&counts&&<Table aria-label="Current workload by family"><thead><tr><th>Family</th><th>Running</th><th>Waiting</th><th>Failed</th><th>Uncertain</th></tr></thead><tbody>{workload.map(row=><tr key={row.name}><td>{row.name}</td><td>{row.running}</td><td>{row.waiting}</td><td>{row.failed}</td><td>{row.uncertain}</td></tr>)}</tbody></Table>}</details></>;
}
