export type { IncomingMessage } from "./application/dto/incoming-message.js";
export type { ClockPort } from "./application/ports/clock.js";
export { SystemClock } from "./application/ports/clock.js";
export type { EncryptionPort } from "./application/ports/encryption.js";
export type { LoggerPort } from "./application/ports/logger.js";
export { NoopLogger } from "./application/ports/logger.js";
export type { MemoryRecordRepositoryPort } from "./application/ports/memory-record-repository.js";
export type { SecretDetectorPort } from "./application/ports/secret-detector.js";
export type { TaskExtractorPort } from "./application/ports/task-extractor.js";
export type { ExternalTask, TaskProviderPort } from "./application/ports/task-provider.js";
export type { TaskRepositoryPort } from "./application/ports/task-repository.js";
export type { TaskSyncRepositoryPort } from "./application/ports/task-sync-repository.js";
export { ProcessIncomingMessageUseCase } from "./application/use-cases/process-incoming-message.js";
export type { ProcessIncomingMessageResult } from "./application/use-cases/process-incoming-message.js";
export type { MemoryRecord, MemoryRecordKind } from "./domain/memory/memory-record.js";
export type { RedactedContent, SensitiveFinding, SensitiveFindingKind } from "./domain/security/redaction.js";
export { Task } from "./domain/tasks/task.js";
export type { CreateTaskInput, SourceReference, TaskId, TaskPriority, TaskSnapshot, TaskStatus } from "./domain/tasks/task.js";
export { TaskCandidatePolicy } from "./domain/tasks/task-extraction.js";
export type { ExtractedTaskCandidate } from "./domain/tasks/task-extraction.js";
export { RegexSecretDetector } from "./infrastructure/security/regex-secret-detector.js";
export { RuleBasedTaskExtractor } from "./infrastructure/reasoning/rule-based-task-extractor.js";
export { AesGcmEncryption } from "./infrastructure/security/aes-gcm-encryption.js";
export { EncryptedJsonFileStore } from "./infrastructure/memory/encrypted-json-file-store.js";
export { LocalTaskRepository } from "./infrastructure/memory/local-task-repository.js";
export { LocalMemoryRecordRepository } from "./infrastructure/memory/local-memory-record-repository.js";
export { LocalTaskSyncRepository } from "./infrastructure/memory/local-task-sync-repository.js";
export { TelegramUpdateMapper } from "./infrastructure/messaging/telegram/telegram-update-mapper.js";
export type { TelegramUpdate } from "./infrastructure/messaging/telegram/telegram-update-mapper.js";
export { NotionMcpTaskProvider } from "./infrastructure/tasks/notion-mcp-task-provider.js";
export type { NotionMcpTaskProviderConfig } from "./infrastructure/tasks/notion-mcp-task-provider.js";
export { StdioMcpClient } from "./infrastructure/tasks/stdio-mcp-client.js";
export type { JsonValue, McpClient } from "./infrastructure/tasks/mcp-client.js";
export { ConsoleLogger } from "./infrastructure/logger/console-logger.js";
export { createTelegramWebhookHandler } from "./interfaces/telegram-webhook/create-telegram-webhook-handler.js";
