import * as React from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,Archive,ArrowUpRight,BrainCircuit,Database,FolderInput,GitFork,Home,Menu,PanelLeftClose,PanelLeftOpen,Plug,RefreshCw,Settings,ShieldCheck,Wrench,X} from 'lucide-react';
import {createPages} from './legacy-pages.js';
import {Button,Sheet,Tooltip} from './components/ui/primitives';
import {ThemeSelect} from './lib/theme';
import {refreshResources} from './lib/resource';
const pages=createPages();
const routes=[
 ['overview','Overview',Home,'Your conversations, memory, and assistant at a glance.'],['archive','Archive',Archive,'Find originals and inspect the evidence behind generated text.'],['memory','Memory',BrainCircuit,'Working notes and conversations, separated by profile.'],['honcho','Honcho memory',Database,'Primary memory availability and synchronization.'],['graph','Graph',GitFork,'Explore recorded relationships and their sources.'],
 ['monitoring','Monitoring',Activity,'System health, workflow progress, and historical trends.'],['activity','Activity',ShieldCheck,'Review approvals, permissions, and conversation results.'],
 ['imports','Imports',FolderInput,'Bring Telegram history into your owned archive.'],['spaces','Memory access',ShieldCheck,'Control what each group and topic can use.'],['integrations','Integrations',Plug,'The connected tools behind your personal brain.'],['settings','Settings',Settings,'Telegram access, agent preferences, and privacy.'],['operations','Maintenance',Wrench,'Diagnostics, exports, backups, and recovery.']
] as const;
const groups=[['Knowledge',['overview','archive','memory','honcho','graph']],['Operations',['monitoring','activity']],['Manage',['imports','spaces','integrations','settings','operations']]] as const;
function currentRoute(){const key=location.hash.slice(1).split('?')[0];return routes.some(r=>r[0]===key)?key:'overview';}
function App(){
 const [page,setPage]=React.useState(currentRoute),[mobile,setMobile]=React.useState(false),[collapsed,setCollapsed]=React.useState(()=>{try{return localStorage.getItem('nocheh.sidebar.v1')==='collapsed';}catch{return false;}}),[notice,setNotice]=React.useState<{text:string;error:boolean}|null>(null),[refreshing,setRefreshing]=React.useState(false);
 const heading=React.useRef<HTMLHeadingElement>(null),menu=React.useRef<HTMLButtonElement>(null);
 React.useEffect(()=>{const change=()=>{setPage(currentRoute());setNotice(null);setMobile(false);};addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change);},[]);
 React.useEffect(()=>{heading.current?.focus({preventScroll:true});},[page]);
 const toggle=()=>setCollapsed(value=>{try{localStorage.setItem('nocheh.sidebar.v1',!value?'collapsed':'expanded');}catch{}return !value;});
 const refresh=()=>{refreshResources();setRefreshing(true);setTimeout(()=>setRefreshing(false),500);};
 const notify=React.useCallback((text:string,error=false)=>setNotice({text,error}),[]);
 const route=routes.find(r=>r[0]===page)!;
 const Current=pages[page as keyof typeof pages] as React.ComponentType<any>;
 const navigation=(compact=false)=><><a href="#overview" className="n-brand"><span className="n-mark" aria-hidden="true">ن</span><span className={compact?'sr-only':''}>Nocheh<small>Your personal brain</small></span></a><nav aria-label="Main navigation">{groups.map(([label,keys])=><div className="n-nav-group" key={label}><span className={compact?'sr-only':'n-nav-label'}>{label}</span>{keys.map(key=>{const [id,title,Icon]=routes.find(r=>r[0]===key)!;const link=<a href={'#'+id} aria-current={page===id?'page':undefined} aria-label={compact?title:undefined} onClick={()=>setMobile(false)}><Icon size={18} aria-hidden="true"/><span className={compact?'sr-only':''}>{title}</span></a>;return compact?<Tooltip label={title} key={id}>{link}</Tooltip>:<React.Fragment key={id}>{link}</React.Fragment>;})}</div>)}</nav><div className="n-sidebar-foot"><a href="/hermes/nocheh" title="Open Hermes"><Plug size={16}/><span className={compact?'sr-only':''}>Hermes</span><ArrowUpRight size={14}/></a><a href="/providers/management.html" title="Open provider monitor"><Activity size={16}/><span className={compact?'sr-only':''}>Provider monitor</span><ArrowUpRight size={14}/></a>{!compact&&<small>Local owner dashboard</small>}</div></>;
 return <div className={'nocheh-app'+(collapsed?' sidebar-collapsed':'')+(page==='graph'?' n-graph-active':'')}><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus();}}>Skip to content</a><aside className="n-sidebar">{navigation(collapsed)}<Button className="sidebar-toggle" onClick={toggle} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'}>{collapsed?<PanelLeftOpen size={18}/>:<><PanelLeftClose size={18}/><span>Collapse sidebar</span></>}</Button></aside><Sheet open={mobile} onOpenChange={setMobile} title="Navigation" side="left" returnFocus={menu.current}><div className="mobile-navigation">{navigation()}</div></Sheet><main className="n-main" id="main-content" tabIndex={-1}><header className="n-header"><div className="page-title"><Button className="mobile-menu" size="icon" onClick={()=>setMobile(true)} ref={menu} aria-label="Open navigation"><Menu size={20}/></Button><div><p className="n-eyebrow">NOCHEH / {groups.find(g=>g[1].some(id=>id===page))?.[0]}</p><h1 ref={heading} tabIndex={-1}>{route[1]}</h1><p className="n-page-description">{route[3]}</p></div></div><div className="header-actions"><ThemeSelect/><Button onClick={refresh} aria-label="Refresh page data"><RefreshCw size={15} className={refreshing?'refreshing':''}/><span>Refresh</span></Button></div></header>{notice&&<div className={'n-notice '+(notice.error?'n-error':'')} role={notice.error?'alert':'status'}><span>{notice.text}</span><Button size="icon" variant="ghost" onClick={()=>setNotice(null)} aria-label="Dismiss notification"><X size={16}/></Button></div>}<div className="page-content" key={page}><Current notify={notify} call={pages.call} renderSource={(record:any)=><pages.Source record={record} notify={notify}/>} refresh={0}/></div><footer>Owned sources. Useful memory. Clear operations.</footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
